"""Data part 9: college (NCAA programs) + recruiting & camps."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 19. COLLEGE / NCAA PROGRAMS & CONFERENCES
# ---------------------------------------------------------------------------

COLLEGE: list[dict[str, Any]] = [
    {"id": "col-001", "category": "college", "name": "NCAA Swimming & Diving",
     "type": "Governance", "audience": "Public",
     "description": "Top-level NCAA portal for swimming and diving.",
     "url": "https://www.ncaa.com/sports/swimming-men", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "ncaa"], "verified": "2026-05"},
    {"id": "col-002", "category": "college", "name": "NCAA Division I Men",
     "type": "Division", "audience": "Recruits",
     "description": "Division I men's swimming and diving listings.",
     "url": "https://www.ncaa.com/sports/swimming-men/d1", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "ncaa"], "verified": "2026-05"},
    {"id": "col-003", "category": "college", "name": "NCAA Division III Men",
     "type": "Division", "audience": "Recruits",
     "description": "Division III men's swimming and diving listings.",
     "url": "https://www.ncaa.com/sports/swimming-men/d3", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "ncaa"], "verified": "2026-05"},
    {"id": "col-004", "category": "college", "name": "NAIA Swimming & Diving",
     "type": "Governance", "audience": "Recruits",
     "description": "NAIA swim and dive championship and team listings.",
     "url": "https://www.naia.org/sports/swim/index", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "naia"], "verified": "2026-05"},
    {"id": "col-005", "category": "college", "name": "NJCAA Swimming",
     "type": "Governance", "audience": "Recruits",
     "description": "Junior-college swimming governance.",
     "url": "https://www.njcaa.org/sports/swim/index", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "juco"], "verified": "2026-05"},
    {"id": "col-006", "category": "college", "name": "CSCAA",
     "type": "Coaches Association", "audience": "College coaches",
     "description": "College Swimming & Diving Coaches Association of America.",
     "url": "https://cscaa.org", "pricing": "mixed", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "coaches"], "verified": "2026-05"},
    {"id": "col-007", "category": "college", "name": "SEC Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Southeastern Conference swimming.",
     "url": "https://www.secsports.com/sport/swimming", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-008", "category": "college", "name": "Big Ten Men's Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Big Ten men's swimming and diving.",
     "url": "https://bigten.org/sports/m-swim", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-009", "category": "college", "name": "Big Ten Women's Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Big Ten women's swimming and diving.",
     "url": "https://bigten.org/sports/w-swim", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-010", "category": "college", "name": "ACC Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Atlantic Coast Conference swimming.",
     "url": "https://theacc.com/sports/swimming-and-diving", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-011", "category": "college", "name": "Big 12 Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Big 12 Conference swimming.",
     "url": "https://big12sports.com", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-012", "category": "college", "name": "Ivy League Swimming",
     "type": "Conference", "audience": "Public",
     "description": "Ivy League swimming and diving.",
     "url": "https://ivyleague.com/sports/swimming", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-013", "category": "college", "name": "AAC Swimming",
     "type": "Conference", "audience": "Public",
     "description": "American Athletic Conference swimming.",
     "url": "https://theamerican.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "conference"], "verified": "2026-05"},
    {"id": "col-014", "category": "college", "name": "SwimCloud College Pages",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "Comprehensive college team pages on SwimCloud.",
     "url": "https://www.swimcloud.com/college/", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["college", "recruiting"], "verified": "2026-05"},
    {"id": "col-015", "category": "college", "name": "Pac-12 Conference (defunct as power conference 2025-26)",
     "type": "Conference", "audience": "Historical",
     "description": "Pac-12 Conference; power-conference structure dissolved for 2025–26.",
     "url": "https://pac-12.com", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "defunct",
     "notes": "Member schools redistributed to Big Ten/ACC/Big 12.",
     "tags": ["college", "defunct"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 20. RECRUITING SERVICES & SWIM CAMPS
# ---------------------------------------------------------------------------

RECRUITING: list[dict[str, Any]] = [
    {"id": "rec2-001", "category": "recruiting", "name": "SwimCloud Recruiting",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "Times-based recruiting platform with college matching.",
     "url": "https://www.swimcloud.com/recruiting/", "pricing": "freemium",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-002", "category": "recruiting", "name": "NCSA Swim Recruiting (Men)",
     "type": "Recruiting Service", "audience": "Recruits",
     "description": "Comprehensive recruiting service for male swimmers.",
     "url": "https://www.ncsasports.org/mens-swimming-recruiting",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-003", "category": "recruiting", "name": "NCSA Swim Recruiting (Women)",
     "type": "Recruiting Service", "audience": "Recruits",
     "description": "Comprehensive recruiting service for female swimmers.",
     "url": "https://www.ncsasports.org/womens-swimming-recruiting",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-004", "category": "recruiting", "name": "SportsRecruits",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "Recruiting platform connecting athletes to coaches.",
     "url": "https://www.sportsrecruits.com", "pricing": "freemium", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-005", "category": "recruiting", "name": "Stack Athlete (formerly STACK Sports)",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "All-in-one recruiting and team management tools.",
     "url": "https://www.stacksports.com", "pricing": "freemium", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-006", "category": "recruiting", "name": "BeRecruited",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "Long-running recruiting platform.",
     "url": "https://www.berecruited.com", "pricing": "freemium", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-007", "category": "recruiting", "name": "ACC Recruits",
     "type": "Recruiting Tool", "audience": "Recruits",
     "description": "ACC-focused recruiting platform.",
     "url": "https://accrecruits.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["recruiting"], "verified": "2026-05"},
    {"id": "rec2-008", "category": "recruiting", "name": "SwimIntel",
     "type": "Analytics", "audience": "Recruits/coaches",
     "description": "Recruiting analytics and rankings.",
     "url": "https://swimintel.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["recruiting", "analytics"], "verified": "2026-05"},
    {"id": "rec2-009", "category": "recruiting", "name": "Fitter and Faster Swim Camps",
     "type": "Camps", "audience": "Age-group",
     "description": "U.S. nationwide camps with Olympian clinicians.",
     "url": "https://fitterandfaster.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["camps"], "verified": "2026-05"},
    {"id": "rec2-010", "category": "recruiting", "name": "Nike Swim Camps",
     "type": "Camps", "audience": "Age-group",
     "description": "Camps held at university campuses across the U.S.",
     "url": "https://www.ussportscamps.com/swim", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["camps"], "verified": "2026-05"},
    {"id": "rec2-011", "category": "recruiting", "name": "Nike Stanford Swim Camp",
     "type": "Camp", "audience": "Age-group",
     "description": "Camp at Stanford University.",
     "url": "https://www.ussportscamps.com/swim/nike/stanford-university",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["camps", "stanford"], "verified": "2026-05"},
    {"id": "rec2-012", "category": "recruiting", "name": "Nike California Swim Camp",
     "type": "Camp", "audience": "Age-group",
     "description": "Camp at UC Berkeley.",
     "url": "https://www.ussportscamps.com/swim/nike/uc-berkeley",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["camps", "cal"], "verified": "2026-05"},
    {"id": "rec2-013", "category": "recruiting", "name": "Peak Performance Swim Camp",
     "type": "Camp", "audience": "Competitive",
     "description": "Long-running competitive swim camp.",
     "url": "https://peakperformanceswim.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["camps"], "verified": "2026-05"},
    {"id": "rec2-014", "category": "recruiting", "name": "Total Performance Swim Camp (Kenyon)",
     "type": "Camp", "audience": "Age-group",
     "description": "Camp at Kenyon College.",
     "url": "https://www.totalperformanceswimcamp.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["camps"], "verified": "2026-05"},
    {"id": "rec2-015", "category": "recruiting", "name": "The Race Club Camps",
     "type": "Camps", "audience": "Competitive",
     "description": "Florida and California performance-focused camps.",
     "url": "https://theraceclub.com/camps/", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["camps"], "verified": "2026-05"},
    {"id": "rec2-016", "category": "recruiting", "name": "USA Swimming Find a Team",
     "type": "Directory", "audience": "Public",
     "description": "Tool to locate USA-S clubs nationwide.",
     "url": "https://www.usaswimming.org/find-a-team", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["directory"], "verified": "2026-05"},
]
