"""Data part 6: news, podcasts & gear."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 10. NEWS, COMMUNITIES & MAGAZINES
# ---------------------------------------------------------------------------

NEWS: list[dict[str, Any]] = [
    {"id": "news-001", "category": "news", "name": "SwimSwam",
     "type": "News + Community", "audience": "All",
     "description": "Largest English-language swimming news + community.",
     "url": "https://swimswam.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2012, "status": "active",
     "notes": "Co-founded by Mel Stewart & Garrett McCaffrey.",
     "tags": ["news", "community"], "verified": "2026-05"},
    {"id": "news-002", "category": "news", "name": "Swimming World Magazine",
     "type": "Magazine", "audience": "All",
     "description": "Long-running swim magazine covering competition and history.",
     "url": "https://www.swimmingworldmagazine.com", "pricing": "mixed",
     "region": "global", "language": "en", "year_founded": 1960, "status": "active",
     "notes": "",
     "tags": ["news", "magazine"], "verified": "2026-05"},
    {"id": "news-003", "category": "news", "name": "FloSwimming",
     "type": "Streaming + News", "audience": "All",
     "description": "FloSports streaming and news platform for swimming.",
     "url": "https://www.floswimming.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "FloSports subscription.",
     "tags": ["news", "streaming"], "verified": "2026-05"},
    {"id": "news-004", "category": "news", "name": "State of Swimming",
     "type": "News/Analysis", "audience": "All",
     "description": "Independent swim journalism by Craig Lord.",
     "url": "https://www.stateofswimming.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Successor to SwimVortex.",
     "tags": ["news", "analysis"], "verified": "2026-05"},
    {"id": "news-005", "category": "news", "name": "Swim England news",
     "type": "Federation News", "audience": "UK swimmers",
     "description": "Official Swim England news feed.",
     "url": "https://www.swimming.org", "pricing": "free", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["news", "federation"], "verified": "2026-05"},
    {"id": "news-006", "category": "news", "name": "World Aquatics news",
     "type": "Federation News", "audience": "All",
     "description": "Official World Aquatics news feed.",
     "url": "https://www.worldaquatics.com/news", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["news", "federation"], "verified": "2026-05"},
    {"id": "news-007", "category": "news", "name": "USA Swimming news",
     "type": "Federation News", "audience": "USA swimmers",
     "description": "Official USA Swimming news feed.",
     "url": "https://www.usaswimming.org/news", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["news", "federation"], "verified": "2026-05"},
    {"id": "news-008", "category": "news", "name": "Reddit r/Swimming",
     "type": "Forum", "audience": "All",
     "description": "Largest swim-focused subreddit (~300K members).",
     "url": "https://www.reddit.com/r/Swimming", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["community", "forum"], "verified": "2026-05"},
    {"id": "news-009", "category": "news", "name": "Reddit r/Triathlon",
     "type": "Forum", "audience": "Triathletes",
     "description": "Triathlon community subreddit covering all three disciplines.",
     "url": "https://www.reddit.com/r/triathlon", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["community", "forum"], "verified": "2026-05"},
    {"id": "news-010", "category": "news", "name": "Swimmer's Daily",
     "type": "News Aggregator", "audience": "All",
     "description": "Daily news aggregator from the Faroe Islands.",
     "url": "https://www.swimmersdaily.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Faroe Islands.",
     "tags": ["news", "aggregator"], "verified": "2026-05"},
    {"id": "news-011", "category": "news", "name": "Swim Wire Media",
     "type": "Newsletter", "audience": "All",
     "description": "Swim industry newsletter.",
     "url": "https://swimwiremedia.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["news", "newsletter"], "verified": "2026-05"},
    {"id": "news-012", "category": "news", "name": "Swammy Awards (SwimSwam)",
     "type": "Annual Awards", "audience": "Public",
     "description": "SwimSwam's annual awards recognizing achievements in the sport.",
     "url": "https://swimswam.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2012, "status": "active", "notes": "",
     "tags": ["awards", "news"], "verified": "2026-05"},
    {"id": "news-013", "category": "news", "name": "Slowtwitch",
     "type": "Triathlon News/Forum", "audience": "Triathletes",
     "description": "Long-running triathlon news, forum, and reviews.",
     "url": "https://www.slowtwitch.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 1999, "status": "active", "notes": "",
     "tags": ["news", "triathlon"], "verified": "2026-05"},
    {"id": "news-014", "category": "news", "name": "Outdoor Swimmer (UK)",
     "type": "Magazine", "audience": "Open-water swimmers",
     "description": "UK magazine for outdoor and open-water swimmers.",
     "url": "https://outdoorswimmer.com", "pricing": "mixed", "region": "UK",
     "language": "en", "year_founded": 2011, "status": "active", "notes": "",
     "tags": ["news", "open-water"], "verified": "2026-05"},
    {"id": "news-015", "category": "news", "name": "Aquatics International",
     "type": "Trade Magazine", "audience": "Pool/facility ops",
     "description": "Trade magazine for pool and aquatic facility operations.",
     "url": "https://www.aquaticsintl.com", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["news", "facilities"], "verified": "2026-05"},
    {"id": "news-016", "category": "news", "name": "SwimVortex",
     "type": "News Site (defunct)", "audience": "All",
     "description": "Historic swim journalism site; archive only.",
     "url": "https://www.swimvortex.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "defunct",
     "notes": "Suspended May 2018; successor State of Swimming.",
     "tags": ["news", "defunct"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 11. PODCASTS
# ---------------------------------------------------------------------------

PODCASTS: list[dict[str, Any]] = [
    {"id": "pod-001", "category": "podcasts", "name": "Inside with Brett Hawke",
     "type": "Podcast", "audience": "All",
     "description": "Long-running interview podcast with elite swimmers and coaches.",
     "url": "https://www.youtube.com/@brettleehawke",
     "pricing": "free", "region": "global", "language": "en", "year_founded": 2020,
     "status": "active",
     "notes": "Apple/Spotify/YouTube; 700+ episodes since Feb 2020.",
     "tags": ["podcast", "interview"], "verified": "2026-05"},
    {"id": "pod-002", "category": "podcasts", "name": "The Swim Brief",
     "type": "Podcast", "audience": "All",
     "description": "Weekly swim news and analysis.",
     "url": "https://chrisdcoach.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2017, "status": "active",
     "notes": "Host Chris DeSantis.",
     "tags": ["podcast", "news"], "verified": "2026-05"},
    {"id": "pod-003", "category": "podcasts", "name": "Effortless Swimming Podcast",
     "type": "Podcast", "audience": "Adults, triathletes",
     "description": "400+ episodes on adult and triathlon swimming.",
     "url": "https://effortlessswimming.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2015, "status": "active",
     "notes": "Host Brenton Ford.",
     "tags": ["podcast", "technique"], "verified": "2026-05"},
    {"id": "pod-004", "category": "podcasts", "name": "Swim Chats",
     "type": "Podcast", "audience": "Open-water swimmers",
     "description": "NZ-based open-water swim podcast.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "NZ",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Host Shona Riddell.",
     "tags": ["podcast", "open-water"], "verified": "2026-05"},
    {"id": "pod-005", "category": "podcasts", "name": "Behind the Blocks",
     "type": "Podcast", "audience": "All",
     "description": "WiSP Sports show featuring elite athletes.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2020, "status": "active",
     "notes": "Host Kaitlin Sandeno.",
     "tags": ["podcast", "interview"], "verified": "2026-05"},
    {"id": "pod-006", "category": "podcasts", "name": "Champion's Mojo",
     "type": "Podcast", "audience": "Masters",
     "description": "Weekly podcast focused on masters swimming.",
     "url": "https://www.championsmojo.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Host Kelly Palace.",
     "tags": ["podcast", "masters"], "verified": "2026-05"},
    {"id": "pod-007", "category": "podcasts", "name": "Kick Set",
     "type": "Podcast", "audience": "USA-S members",
     "description": "Official USA Swimming podcast.",
     "url": "https://www.usaswimming.org/utility/landing-pages/kick-set",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": None,
     "status": "active",
     "notes": "Hosts Matt Barbini & Elizabeth Beisel.",
     "tags": ["podcast", "ngb"], "verified": "2026-05"},
    {"id": "pod-008", "category": "podcasts", "name": "SwimSwam Podcast",
     "type": "Podcast", "audience": "All",
     "description": "Weekly news podcast from the SwimSwam team.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Hosts Coleman Hodges & Mel Stewart.",
     "tags": ["podcast", "news"], "verified": "2026-05"},
    {"id": "pod-009", "category": "podcasts", "name": "Unfiltered Waters",
     "type": "Podcast", "audience": "All",
     "description": "Conversations with elite swimmers from two Olympians.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2023, "status": "active",
     "notes": "Hosts Katie Hoff & Missy Franklin.",
     "tags": ["podcast", "interview"], "verified": "2026-05"},
    {"id": "pod-010", "category": "podcasts", "name": "Propulsion Swimming Podcast",
     "type": "Podcast", "audience": "GB swimmers",
     "description": "British-focused swim podcast on Acast.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "GB",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Hosts Scott Howarth & Dan Woodward.",
     "tags": ["podcast", "gb"], "verified": "2026-05"},
    {"id": "pod-011", "category": "podcasts", "name": "Ultimate Swimmer",
     "type": "Podcast", "audience": "All",
     "description": "Performance-focused swim podcast.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Host Josh Davis (3x Olympic gold).",
     "tags": ["podcast", "performance"], "verified": "2026-05"},
    {"id": "pod-012", "category": "podcasts", "name": "MySwimPro Podcast",
     "type": "Podcast", "audience": "All",
     "description": "Sporadic podcast from MySwimPro team.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Sporadic release schedule.",
     "tags": ["podcast"], "verified": "2026-05"},
    {"id": "pod-013", "category": "podcasts", "name": "Tri Swim Coach",
     "type": "Podcast", "audience": "Triathletes",
     "description": "Triathlon swim-focused podcast.",
     "url": "https://podcasts.apple.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Host Kevin Koskella.",
     "tags": ["podcast", "triathlon"], "verified": "2026-05"},
    {"id": "pod-014", "category": "podcasts", "name": "Scientific Triathlon (That Triathlon Show)",
     "type": "Podcast", "audience": "Triathletes",
     "description": "Science-driven triathlon training podcast.",
     "url": "https://scientifictriathlon.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Host Mikael Eriksson.",
     "tags": ["podcast", "triathlon", "science"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 12. GEAR, EQUIPMENT & REVIEWS
# ---------------------------------------------------------------------------

GEAR: list[dict[str, Any]] = [
    {"id": "gear-001", "category": "gear", "name": "SwimOutlet",
     "type": "Retailer", "audience": "All",
     "description": "Largest U.S. online swim retailer; curated 12U buyer guides.",
     "url": "https://www.swimoutlet.com", "pricing": "varies", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["retailer"], "verified": "2026-05"},
    {"id": "gear-002", "category": "gear", "name": "Kiefer",
     "type": "Retailer", "audience": "All",
     "description": "Long-running U.S. swim retailer (since 1947).",
     "url": "https://www.kiefer.com", "pricing": "varies", "region": "USA",
     "language": "en", "year_founded": 1947, "status": "active", "notes": "",
     "tags": ["retailer"], "verified": "2026-05"},
    {"id": "gear-003", "category": "gear", "name": "ProSwimwear",
     "type": "Retailer", "audience": "All",
     "description": "UK-based competitive swim retailer.",
     "url": "https://www.proswimwear.co.uk", "pricing": "varies", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["retailer"], "verified": "2026-05"},
    {"id": "gear-004", "category": "gear", "name": "Simply Swim",
     "type": "Retailer", "audience": "All",
     "description": "UK swim retailer for all levels.",
     "url": "https://www.simplyswim.com", "pricing": "varies", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["retailer"], "verified": "2026-05"},
    {"id": "gear-005", "category": "gear", "name": "FINIS",
     "type": "Brand", "audience": "All",
     "description": "Innovation-focused brand; Tempo Trainer Pro.",
     "url": "https://www.finisswim.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-006", "category": "gear", "name": "TYR",
     "type": "Brand", "audience": "All",
     "description": "Major competitive brand; Thresher and Venzo lines.",
     "url": "https://www.tyr.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-007", "category": "gear", "name": "Speedo USA / Global",
     "type": "Brand", "audience": "All",
     "description": "Top global swim brand; LZR Pure Intent / Valor lines.",
     "url": "https://www.speedousa.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Global site: https://www.speedo.com",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-008", "category": "gear", "name": "Arena",
     "type": "Brand", "audience": "All",
     "description": "Major competitive brand; Carbon Air2 / Primo lines.",
     "url": "https://www.arenawaterinstinct.com", "pricing": "varies",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-009", "category": "gear", "name": "Mizuno",
     "type": "Brand", "audience": "All",
     "description": "Competitive swim brand; GX Sonic VI line.",
     "url": "https://www.mizuno.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Regional websites.",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-010", "category": "gear", "name": "MP Michael Phelps",
     "type": "Brand", "audience": "All",
     "description": "Phelps-branded line; XCEED goggles.",
     "url": "https://www.michaelphelps.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-011", "category": "gear", "name": "Aqua Sphere",
     "type": "Brand", "audience": "All",
     "description": "Goggle and gear brand; Vista and Kayenne lines.",
     "url": "https://www.aquasphereswim.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-012", "category": "gear", "name": "Funky Trunks / Funkita",
     "type": "Brand", "audience": "All",
     "description": "Australian brand known for graphic prints.",
     "url": "https://www.funkytrunks.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand"], "verified": "2026-05"},
    {"id": "gear-013", "category": "gear", "name": "BlueSeventy",
     "type": "Wetsuits", "audience": "Triathletes / open water",
     "description": "Wetsuit specialist; Helix and Reaction lines.",
     "url": "https://www.blueseventy.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand", "wetsuit"], "verified": "2026-05"},
    {"id": "gear-014", "category": "gear", "name": "ROKA",
     "type": "Tri Brand", "audience": "Triathletes",
     "description": "Triathlon brand; Maverick X.3 wetsuit and R1 goggles.",
     "url": "https://www.roka.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand", "triathlon"], "verified": "2026-05"},
    {"id": "gear-015", "category": "gear", "name": "Orca",
     "type": "Tri Brand", "audience": "Triathletes",
     "description": "New Zealand brand founded 1992.",
     "url": "https://www.orca.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": 1992, "status": "active", "notes": "",
     "tags": ["brand", "triathlon"], "verified": "2026-05"},
    {"id": "gear-016", "category": "gear", "name": "Zone3",
     "type": "Tri Brand", "audience": "Triathletes",
     "description": "UK triathlon and open-water brand.",
     "url": "https://zone3.com", "pricing": "varies", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand", "triathlon"], "verified": "2026-05"},
    {"id": "gear-017", "category": "gear", "name": "HUUB",
     "type": "Tri Brand", "audience": "Triathletes",
     "description": "UK triathlon brand.",
     "url": "https://huubdesign.com", "pricing": "varies", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand", "triathlon"], "verified": "2026-05"},
    {"id": "gear-018", "category": "gear", "name": "Jaked",
     "type": "Race Suit Brand", "audience": "Competitive",
     "description": "Italian race-suit specialist.",
     "url": "https://www.jaked.com", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["brand", "racesuit"], "verified": "2026-05"},
    {"id": "gear-019", "category": "gear", "name": "World Aquatics Approved Swimwear",
     "type": "Reference List", "audience": "Competitive",
     "description": "Official approved-swimsuit registry from World Aquatics.",
     "url": "https://www.worldaquatics.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["reference", "rules"], "verified": "2026-05"},
    {"id": "gear-020", "category": "gear", "name": "USA Swimming Tech Suit (12U) Restrictions",
     "type": "Reference Document", "audience": "Coaches/parents",
     "description": "12-and-under tech-suit restrictions effective Sep 1, 2020.",
     "url": "https://www.usaswimming.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Effective Sep 1, 2020.",
     "tags": ["reference", "rules"], "verified": "2026-05"},
    {"id": "gear-021", "category": "gear", "name": "220 Triathlon",
     "type": "Reviews", "audience": "Triathletes",
     "description": "UK triathlon magazine since 1989; comprehensive gear reviews.",
     "url": "https://www.220triathlon.com", "pricing": "mixed", "region": "UK",
     "language": "en", "year_founded": 1989, "status": "active", "notes": "",
     "tags": ["reviews", "triathlon"], "verified": "2026-05"},
    {"id": "gear-022", "category": "gear", "name": "Triathlete Magazine",
     "type": "Reviews", "audience": "Triathletes",
     "description": "U.S.-based triathlon magazine with regular gear coverage.",
     "url": "https://www.triathlete.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["reviews", "triathlon"], "verified": "2026-05"},
    {"id": "gear-023", "category": "gear", "name": "SwimSwam Gear",
     "type": "Reviews", "audience": "All",
     "description": "Annual tech-suit and goggles reviews.",
     "url": "https://swimswam.com/training/gear/", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["reviews"], "verified": "2026-05"},
    {"id": "gear-024", "category": "gear", "name": "DC Rainmaker",
     "type": "Tech Reviews", "audience": "All",
     "description": "Gold standard for sports tech reviews including swim wearables.",
     "url": "https://www.dcrainmaker.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["reviews", "tech"], "verified": "2026-05"},
    {"id": "gear-025", "category": "gear", "name": "YourSwimLog Gear Guides",
     "type": "Reviews", "audience": "All",
     "description": "Equipment-focused buyer guides.",
     "url": "https://www.yourswimlog.com/swimming-accessories/",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["reviews"], "verified": "2026-05"},
]
