"""Data part 8: para + drowning prevention + records."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 16. PARA SWIMMING & ADAPTIVE RESOURCES
# ---------------------------------------------------------------------------

PARA: list[dict[str, Any]] = [
    {"id": "para-001", "category": "para", "name": "World Para Swimming",
     "type": "International Federation", "audience": "Para athletes",
     "description": "Paralympic governance; classification rules and World Championships.",
     "url": "https://www.paralympic.org/swimming",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "HQ Bonn, Germany.",
     "tags": ["para", "federation"], "verified": "2026-05"},
    {"id": "para-002", "category": "para", "name": "World Para Swimming Classification Rules (2022)",
     "type": "Reference Document", "audience": "Coaches/classifiers",
     "description": "Official classification rules in effect since 2022.",
     "url": "https://www.paralympic.org/swimming/rules", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["para", "rules"], "verified": "2026-05"},
    {"id": "para-003", "category": "para", "name": "U.S. Paralympics Swimming",
     "type": "Para NGB", "audience": "US para athletes",
     "description": "U.S. Paralympic swimming arm under USOPC.",
     "url": "https://www.usparaswimming.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "usa"], "verified": "2026-05"},
    {"id": "para-004", "category": "para", "name": "Special Olympics Aquatics",
     "type": "Adaptive Sports", "audience": "Intellectual disability",
     "description": "Adaptive aquatics programming for athletes with intellectual disabilities.",
     "url": "https://www.specialolympics.org/our-work/sports/aquatics",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["para", "special-olympics"], "verified": "2026-05"},
    {"id": "para-005", "category": "para", "name": "Move United",
     "type": "Adaptive Sports Network", "audience": "Adaptive athletes",
     "description": "200+ adaptive sport organizations across the U.S.",
     "url": "https://moveunitedsport.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Network of chapters.",
     "tags": ["para", "adaptive"], "verified": "2026-05"},
    {"id": "para-006", "category": "para", "name": "Aquatics GB Para",
     "type": "Federation Resource", "audience": "GB para athletes",
     "description": "Para portal from Aquatics GB.",
     "url": "https://www.britishswimming.org/parasport", "pricing": "free",
     "region": "GB", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["para", "gb"], "verified": "2026-05"},
    {"id": "para-007", "category": "para", "name": "Swim England Para Swimming",
     "type": "Federation Resource", "audience": "Para athletes",
     "description": "Para swimming pathway from Swim England.",
     "url": "https://www.swimming.org/parapathway", "pricing": "free", "region": "England",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "england"], "verified": "2026-05"},
    {"id": "para-008", "category": "para", "name": "Swimming Canada Para",
     "type": "Federation Resource", "audience": "Canadian para athletes",
     "description": "Para portal from Swimming Canada.",
     "url": "https://www.swimming.ca/en/paraswimming/", "pricing": "free", "region": "Canada",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "canada"], "verified": "2026-05"},
    {"id": "para-009", "category": "para", "name": "Canadian Paralympic Committee",
     "type": "National Paralympic Committee", "audience": "Canadian para athletes",
     "description": "Canada's national Paralympic committee.",
     "url": "https://paralympic.ca", "pricing": "free", "region": "Canada",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "canada"], "verified": "2026-05"},
    {"id": "para-010", "category": "para", "name": "Autism Swim",
     "type": "Specialized Program", "audience": "Autistic individuals + families",
     "description": "Specialized water-safety and swimming program for autistic individuals.",
     "url": "https://autismswim.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "autism"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 17. DROWNING PREVENTION & PUBLIC HEALTH
# ---------------------------------------------------------------------------

DROWNING_PREVENTION: list[dict[str, Any]] = [
    {"id": "dp-001", "category": "drowning_prevention", "name": "CDC Drowning Prevention",
     "type": "Government Resource", "audience": "Public",
     "description": "Drowning data and prevention resources from the U.S. CDC.",
     "url": "https://www.cdc.gov/drowning/", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "policy"], "verified": "2026-05"},
    {"id": "dp-002", "category": "drowning_prevention", "name": "WHO Global Status Report on Drowning Prevention 2024",
     "type": "Report", "audience": "Researchers/policy",
     "description": "Latest global drowning data and policy framework from WHO.",
     "url": "https://www.who.int/publications/i/item/9789240094703",
     "pricing": "free", "region": "global", "language": "en", "year_founded": 2024,
     "status": "active", "notes": "",
     "tags": ["drowning-prevention", "report"], "verified": "2026-05"},
    {"id": "dp-003", "category": "drowning_prevention", "name": "WHO Implementation Guide",
     "type": "Guide", "audience": "Policy/practitioners",
     "description": "WHO's guide to preventing drowning at scale.",
     "url": "https://www.who.int/publications/i/item/9789240050617",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["drowning-prevention", "guide"], "verified": "2026-05"},
    {"id": "dp-004", "category": "drowning_prevention", "name": "American Academy of Pediatrics Water Safety",
     "type": "Medical Guidance", "audience": "Pediatricians/parents",
     "description": "AAP water-safety guidelines for children.",
     "url": "https://www.healthychildren.org/English/safety-prevention/at-play/Pages/Water-Safety-And-Young-Children.aspx",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["drowning-prevention", "medical"], "verified": "2026-05"},
    {"id": "dp-005", "category": "drowning_prevention", "name": "Lifesaving Foundation Ireland",
     "type": "Foundation", "audience": "All",
     "description": "Drowning prevention research and rescue education in Ireland.",
     "url": "https://lifesavingfoundation.ie", "pricing": "free", "region": "Ireland",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "foundation"], "verified": "2026-05"},
    {"id": "dp-006", "category": "drowning_prevention", "name": "Surf Life Saving Australia",
     "type": "Lifesaving Body", "audience": "Beachgoers",
     "description": "Australia's coastal water-safety organization since 1907.",
     "url": "https://sls.com.au", "pricing": "mixed", "region": "Australia",
     "language": "en", "year_founded": 1907, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "lifesaving"], "verified": "2026-05"},
    {"id": "dp-007", "category": "drowning_prevention", "name": "United States Lifesaving Association",
     "type": "Lifeguard Association", "audience": "Beach lifeguards",
     "description": "U.S. national lifeguard standards and rip-current education.",
     "url": "https://www.usla.org", "pricing": "mixed", "region": "USA",
     "language": "en", "year_founded": 1964, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "lifesaving"], "verified": "2026-05"},
    {"id": "dp-008", "category": "drowning_prevention", "name": "Royal Life Saving Society Commonwealth",
     "type": "Lifesaving Society", "audience": "Commonwealth nations",
     "description": "Royal Life Saving Society UK and Commonwealth.",
     "url": "https://www.rlss.org.uk", "pricing": "mixed", "region": "UK",
     "language": "en", "year_founded": 1891, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "lifesaving"], "verified": "2026-05"},
    {"id": "dp-009", "category": "drowning_prevention", "name": "International Life Saving Federation",
     "type": "International Body", "audience": "International orgs",
     "description": "Global coordinating body for lifesaving organizations.",
     "url": "https://www.ilsf.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "international"], "verified": "2026-05"},
    {"id": "dp-010", "category": "drowning_prevention", "name": "U.S. National Water Safety Action Plan",
     "type": "Policy Document", "audience": "Policy",
     "description": "U.S. national framework with 99 actions for 2023–2032.",
     "url": "https://watersafetyusa.org/the-u-s-national-water-safety-action-plan/",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": 2023,
     "status": "active", "notes": "",
     "tags": ["drowning-prevention", "policy"], "verified": "2026-05"},
    {"id": "dp-011", "category": "drowning_prevention", "name": "Safe Kids Worldwide",
     "type": "Foundation", "audience": "Public",
     "description": "Child injury prevention with substantial water-safety programs.",
     "url": "https://www.safekids.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["drowning-prevention", "foundation"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 18. RECORDS, RANKINGS & RESULTS DATABASES
# ---------------------------------------------------------------------------

RECORDS: list[dict[str, Any]] = [
    {"id": "rec-001", "category": "records", "name": "World Aquatics Rankings",
     "type": "Rankings Database", "audience": "Public",
     "description": "Official world rankings from World Aquatics.",
     "url": "https://www.worldaquatics.com/swimming/rankings",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["records", "rankings"], "verified": "2026-05"},
    {"id": "rec-002", "category": "records", "name": "World Aquatics Masters Top 10",
     "type": "Rankings Database", "audience": "Public",
     "description": "Masters Top-10 listings from World Aquatics.",
     "url": "https://www.worldaquatics.com/swimming/masters",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["records", "masters"], "verified": "2026-05"},
    {"id": "rec-003", "category": "records", "name": "USA Swimming Times Hub",
     "type": "Times Database", "audience": "Public",
     "description": "Search portal for USA Swimming times.",
     "url": "https://www.usaswimming.org/times", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "usa"], "verified": "2026-05"},
    {"id": "rec-004", "category": "records", "name": "USA Swimming Individual Times Search",
     "type": "Times Database", "audience": "Public",
     "description": "Individual swimmer times search.",
     "url": "https://swims.usaswimming.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "usa"], "verified": "2026-05"},
    {"id": "rec-005", "category": "records", "name": "USA Swimming TimesEventRank",
     "type": "Rankings Tool", "audience": "Public",
     "description": "Event rankings tool.",
     "url": "https://www.usaswimming.org/times", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "usa"], "verified": "2026-05"},
    {"id": "rec-006", "category": "records", "name": "USA Swimming World Rankings Tool",
     "type": "Rankings Tool", "audience": "Public",
     "description": "USA Swimming's tool comparing US athletes to world rankings.",
     "url": "https://www.usaswimming.org/times", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "usa"], "verified": "2026-05"},
    {"id": "rec-007", "category": "records", "name": "USA Swimming SWIMS Database",
     "type": "Times Database", "audience": "Coaches/officials",
     "description": "Official USA Swimming meet results database.",
     "url": "https://swims.usaswimming.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "usa"], "verified": "2026-05"},
    {"id": "rec-008", "category": "records", "name": "SwimCloud",
     "type": "Times Database", "audience": "Athletes/recruiters",
     "description": "Times database with college rankings and recruiting tools.",
     "url": "https://www.swimcloud.com", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "rankings"], "verified": "2026-05"},
    {"id": "rec-009", "category": "records", "name": "SwimCloud College Rankings",
     "type": "Rankings", "audience": "Recruits",
     "description": "U.S. college team rankings (D1/D2/D3/NAIA).",
     "url": "https://www.swimcloud.com/college/", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "college"], "verified": "2026-05"},
    {"id": "rec-010", "category": "records", "name": "Swimrankings.net",
     "type": "Times Database", "audience": "Public",
     "description": "European-focused historical times database.",
     "url": "https://www.swimrankings.net", "pricing": "free", "region": "europe",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "europe"], "verified": "2026-05"},
    {"id": "rec-011", "category": "records", "name": "Swim England Results",
     "type": "Times Database", "audience": "UK swimmers",
     "description": "Times and rankings from Swim England.",
     "url": "https://swimmingresults.org", "pricing": "free", "region": "England",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "england"], "verified": "2026-05"},
    {"id": "rec-012", "category": "records", "name": "Aquatics GB Rankings",
     "type": "Rankings", "audience": "GB swimmers",
     "description": "Aquatics GB rankings portal.",
     "url": "https://www.britishswimming.org/rankings", "pricing": "free", "region": "GB",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "gb"], "verified": "2026-05"},
    {"id": "rec-013", "category": "records", "name": "Swimming Canada Records",
     "type": "Records", "audience": "Canadian swimmers",
     "description": "Swimming Canada records and rankings.",
     "url": "https://www.swimming.ca/en/results-rankings/", "pricing": "free",
     "region": "Canada", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["records", "canada"], "verified": "2026-05"},
    {"id": "rec-014", "category": "records", "name": "Swimming Australia Rankings",
     "type": "Rankings", "audience": "AUS swimmers",
     "description": "Swimming Australia rankings.",
     "url": "https://www.swimming.org.au", "pricing": "free", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "australia"], "verified": "2026-05"},
    {"id": "rec-015", "category": "records", "name": "Results Central (Australia)",
     "type": "Times Database", "audience": "AUS swimmers",
     "description": "Australian times database.",
     "url": "https://resultscentral.com.au", "pricing": "free", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "australia"], "verified": "2026-05"},
    {"id": "rec-016", "category": "records", "name": "Japan Aquatics Results",
     "type": "Results Portal", "audience": "Japanese swimmers",
     "description": "Japan Aquatics results and rankings.",
     "url": "https://aquatics.or.jp", "pricing": "free", "region": "Japan",
     "language": "ja", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "japan"], "verified": "2026-05"},
    {"id": "rec-017", "category": "records", "name": "Seiko EN Live Results",
     "type": "Live Results", "audience": "Public",
     "description": "Real-time results provider for major meets.",
     "url": "https://www.seiko-eas.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "live"], "verified": "2026-05"},
    {"id": "rec-018", "category": "records", "name": "Olympics.com Paris 2024 Swimming",
     "type": "Olympic Results", "audience": "Public",
     "description": "Official Paris 2024 Olympic swimming results.",
     "url": "https://olympics.com/en/paris-2024/sports/swimming",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["records", "olympics"], "verified": "2026-05"},
    {"id": "rec-019", "category": "records", "name": "Olympedia Swimming",
     "type": "Historical Database", "audience": "Researchers",
     "description": "Comprehensive Olympic swimming history.",
     "url": "https://www.olympedia.org/sports/SWM", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "history"], "verified": "2026-05"},
    {"id": "rec-020", "category": "records", "name": "Olympedia World Record Holders",
     "type": "Reference List", "audience": "Researchers",
     "description": "Olympedia's swimming world-record-holders list.",
     "url": "https://www.olympedia.org/lists/77/manual",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["records", "history"], "verified": "2026-05"},
    {"id": "rec-021", "category": "records", "name": "USMS Records",
     "type": "Records", "audience": "USMS members",
     "description": "USMS national, world, and zone records.",
     "url": "https://www.usms.org/comp/records-tt", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "masters"], "verified": "2026-05"},
    {"id": "rec-022", "category": "records", "name": "USMS Top 10",
     "type": "Rankings", "audience": "USMS members",
     "description": "USMS annual Top-10 listings.",
     "url": "https://www.usms.org/comp/tt/toptimes.php", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "masters"], "verified": "2026-05"},
    {"id": "rec-023", "category": "records", "name": "NCAA Division I Men Records",
     "type": "Records", "audience": "Public",
     "description": "NCAA D1 men's swimming and diving records.",
     "url": "https://www.ncaa.com/sports/swimming-men/d1", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "ncaa"], "verified": "2026-05"},
    {"id": "rec-024", "category": "records", "name": "NCAA Division I Women Records",
     "type": "Records", "audience": "Public",
     "description": "NCAA D1 women's swimming and diving records.",
     "url": "https://www.ncaa.com/sports/swimming-women/d1", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "ncaa"], "verified": "2026-05"},
    {"id": "rec-025", "category": "records", "name": "NFHS Records",
     "type": "HS Records", "audience": "Public",
     "description": "U.S. high-school national records (boys and girls).",
     "url": "https://www.nfhs.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "high-school"], "verified": "2026-05"},
    {"id": "rec-026", "category": "records", "name": "NISCA",
     "type": "Coaches Association", "audience": "HS coaches",
     "description": "U.S. high-school swim coaches association with records and All-America lists.",
     "url": "https://www.niscaonline.org", "pricing": "mixed", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "high-school"], "verified": "2026-05"},
    {"id": "rec-027", "category": "records", "name": "nhsswim.net",
     "type": "HS Records Aggregator", "audience": "Public",
     "description": "U.S. high-school swimming record aggregator.",
     "url": "https://www.nhsswim.net", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "high-school"], "verified": "2026-05"},
    {"id": "rec-028", "category": "records", "name": "Swimnerd Live",
     "type": "Live Streaming", "audience": "Public",
     "description": "Live meet streaming and timing solutions.",
     "url": "https://swimnerd.com", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["live", "tech"], "verified": "2026-05"},
    {"id": "rec-029", "category": "records", "name": "Hy-Tek Meet Manager",
     "type": "Meet Software", "audience": "Meet directors",
     "description": "Industry-standard meet-management software.",
     "url": "https://hytek.active.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["software", "meets"], "verified": "2026-05"},
    {"id": "rec-030", "category": "records", "name": "Meet Mobile",
     "type": "Mobile App", "audience": "Public",
     "description": "Live meet results app from Active Network.",
     "url": "https://www.active.com/meetmobile", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["app", "meets"], "verified": "2026-05"},
    {"id": "rec-031", "category": "records", "name": "Swim Standards",
     "type": "Time Standards", "audience": "Public",
     "description": "Looks up qualifying time standards for U.S. championship meets.",
     "url": "https://swimstandards.com", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["records", "standards"], "verified": "2026-05"},
    {"id": "rec-032", "category": "records", "name": "International Swimming Hall of Fame",
     "type": "Historical Archive", "audience": "Public",
     "description": "Aquatic-history archive and museum.",
     "url": "https://ishof.org", "pricing": "free", "region": "global", "language": "en",
     "year_founded": 1965, "status": "active", "notes": "",
     "tags": ["history", "museum"], "verified": "2026-05"},
]
