"""Data part 2: learn-to-swim & technique resources."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 2. LEARN-TO-SWIM & WATER SAFETY PROGRAMS
# ---------------------------------------------------------------------------

LEARN_TO_SWIM: list[dict[str, Any]] = [
    {"id": "lts-001", "category": "learn_to_swim",
     "name": "American Red Cross Learn to Swim", "type": "Curriculum",
     "audience": "6 mo–adult; 6 levels",
     "description": "U.S. industry-standard learn-to-swim curriculum delivered by certified Water Safety Instructors.",
     "url": "https://www.redcross.org/take-a-class/swimming",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": 1914,
     "status": "active", "notes": "Pricing set by local providers.",
     "tags": ["lts", "water-safety", "redcross"], "verified": "2026-05"},
    {"id": "lts-002", "category": "learn_to_swim",
     "name": "YMCA Swim Lessons", "type": "Curriculum",
     "audience": "6 mo–adult",
     "description": "Swim Starters / Basics / Strokes pathway; serves over a million children annually.",
     "url": "https://www.ymca.org/what-we-do/healthy-living/water-safety",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": 1909,
     "status": "active", "notes": "Financial assistance available.",
     "tags": ["lts", "water-safety", "ymca"], "verified": "2026-05"},
    {"id": "lts-003", "category": "learn_to_swim",
     "name": "Infant Swimming Resource (ISR)", "type": "Self-Rescue Curriculum",
     "audience": "6 mo–6 yr",
     "description": "Self-Rescue method delivered in 1:1 lessons; over 19 million lessons delivered.",
     "url": "https://www.infantswim.com/", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["lts", "infant", "self-rescue"], "verified": "2026-05"},
    {"id": "lts-004", "category": "learn_to_swim",
     "name": "SwimAmerica (ASCA)", "type": "Curriculum",
     "audience": "All ages; 10 levels",
     "description": "ASCA's 900-site U.S. learn-to-swim program; bridges to competitive swimming.",
     "url": "https://www.swimamerica.org/", "pricing": "paid", "region": "USA", "language": "en",
     "year_founded": 1987, "status": "active", "notes": "",
     "tags": ["lts", "competitive-pathway"], "verified": "2026-05"},
    {"id": "lts-005", "category": "learn_to_swim",
     "name": "Swim England Learn to Swim Framework", "type": "National Framework",
     "audience": "Ages 4–11 + adult",
     "description": "England's national 7-stage framework with Pre-School and Adult adaptations.",
     "url": "https://www.swimming.org/learntoswim/", "pricing": "paid", "region": "England", "language": "en",
     "year_founded": None, "status": "active", "notes": "Delivered through licensed centres.",
     "tags": ["lts", "framework"], "verified": "2026-05"},
    {"id": "lts-006", "category": "learn_to_swim",
     "name": "AustSwim", "type": "Teacher RTO",
     "audience": "Swim teachers (cert)",
     "description": "Australia's national teacher accreditation; 400K+ teachers trained since 1979.",
     "url": "https://austswim.com.au/", "pricing": "paid", "region": "Australia", "language": "en",
     "year_founded": 1979, "status": "active", "notes": "RTO ID 104975.",
     "tags": ["lts", "certification"], "verified": "2026-05"},
    {"id": "lts-007", "category": "learn_to_swim",
     "name": "SWIM Coaches & Teachers Australia", "type": "Industry Body",
     "audience": "Schools & teachers",
     "description": "Endorses 600+ swim schools; runs SWIMSAFER program.",
     "url": "https://swim.org.au/", "pricing": "paid", "region": "Australia", "language": "en",
     "year_founded": None, "status": "rebranded", "notes": "Replaces former Swim Australia at swimaustralia.org.au.",
     "tags": ["lts", "australia"], "verified": "2026-05"},
    {"id": "lts-008", "category": "learn_to_swim",
     "name": "Lifesaving Society Canada - Swim for Life", "type": "Curriculum",
     "audience": "Parent & Tot–Adult",
     "description": "Canadian national learn-to-swim with embedded Water Smart education.",
     "url": "https://www.lifesavingsociety.com/", "pricing": "paid", "region": "Canada", "language": "en",
     "year_founded": None, "status": "active", "notes": "Includes Swim to Survive.",
     "tags": ["lts", "water-safety"], "verified": "2026-05"},
    {"id": "lts-009", "category": "learn_to_swim",
     "name": "British Swim School", "type": "Franchise School",
     "audience": "3 mo–adult",
     "description": "Survival-first franchise with 5 levels; international footprint.",
     "url": "https://britishswimschool.com/", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": 1981, "status": "active", "notes": "",
     "tags": ["lts", "franchise"], "verified": "2026-05"},
    {"id": "lts-010", "category": "learn_to_swim",
     "name": "Goldfish Swim School", "type": "Franchise School",
     "audience": "4 mo–12 yr",
     "description": "Science of SwimPlay®; 90°F pools; 200+ schools across North America.",
     "url": "https://goldfishswimschool.com/", "pricing": "paid", "region": "USA/Canada", "language": "en",
     "year_founded": None, "status": "active", "notes": "Top-ranked swim franchise in U.S.",
     "tags": ["lts", "franchise"], "verified": "2026-05"},
    {"id": "lts-011", "category": "learn_to_swim",
     "name": "SafeSplash + SwimLabs", "type": "Franchise School",
     "audience": "All ages",
     "description": "Swim lessons combined with video-analysis training labs.",
     "url": "https://www.safesplash.com/", "pricing": "paid", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "NDPA Platinum LTS partner.",
     "tags": ["lts", "video-analysis"], "verified": "2026-05"},
    {"id": "lts-012", "category": "learn_to_swim",
     "name": "Aqua-Tots", "type": "Franchise School",
     "audience": "4 mo–12 yr",
     "description": "Indoor 90°F pools; international franchise network.",
     "url": "https://www.aqua-tots.com/", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["lts", "franchise"], "verified": "2026-05"},
    {"id": "lts-013", "category": "learn_to_swim",
     "name": "Royal Life Saving Society UK", "type": "Lifesaving Society",
     "audience": "All",
     "description": "Founded 1891; certifies ~93% of UK pool lifeguards.",
     "url": "https://www.rlss.org.uk/", "pricing": "mixed", "region": "UK", "language": "en",
     "year_founded": 1891, "status": "active", "notes": "Royal patronage.",
     "tags": ["water-safety", "lifeguard"], "verified": "2026-05"},
    {"id": "lts-014", "category": "learn_to_swim",
     "name": "Royal Life Saving Society Australia", "type": "Lifesaving Society",
     "audience": "All",
     "description": "National non-profit; runs Bronze Medallion and Swim and Survive programs.",
     "url": "https://www.royallifesaving.com.au/", "pricing": "mixed", "region": "Australia", "language": "en",
     "year_founded": 1894, "status": "active", "notes": "",
     "tags": ["water-safety", "lifeguard"], "verified": "2026-05"},
    {"id": "lts-015", "category": "learn_to_swim",
     "name": "WHO Drowning Prevention", "type": "Public Health Initiative",
     "audience": "Global",
     "description": "World Drowning Prevention Day and the Global Status Report 2024 framework.",
     "url": "https://www.who.int/news-room/fact-sheets/detail/drowning",
     "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "~300,000 deaths/yr globally.",
     "tags": ["water-safety", "policy"], "verified": "2026-05"},
    {"id": "lts-016", "category": "learn_to_swim",
     "name": "USA Swimming Foundation Make a Splash", "type": "Initiative",
     "audience": "Children",
     "description": "Five million children served via 850+ Local Partners since 2007.",
     "url": "https://www.usaswimming.org/foundation",
     "pricing": "free", "region": "USA", "language": "en",
     "year_founded": 2007, "status": "active", "notes": "Phillips 66 partner.",
     "tags": ["water-safety", "initiative"], "verified": "2026-05"},
    {"id": "lts-017", "category": "learn_to_swim",
     "name": "Stop Drowning Now", "type": "Curriculum",
     "audience": "K–2; communities",
     "description": "Free Safer 3 framework curriculum for educators and communities.",
     "url": "https://www.stopdrowningnow.org/",
     "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Houses Safer 3 Foundation.",
     "tags": ["water-safety", "education"], "verified": "2026-05"},
    {"id": "lts-018", "category": "learn_to_swim",
     "name": "National Drowning Prevention Alliance (NDPA)", "type": "Coalition",
     "audience": "Public",
     "description": "Premier U.S. drowning-prevention coalition; \"5 Layers of Protection\"; annual conference with AAP.",
     "url": "https://ndpa.org/", "pricing": "mixed", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "HQ Tustin, CA.",
     "tags": ["water-safety", "coalition"], "verified": "2026-05"},
    {"id": "lts-019", "category": "learn_to_swim",
     "name": "ZAC Foundation", "type": "Foundation",
     "audience": "Children 5–9",
     "description": "ZAC Camps via Boys & Girls Clubs in 28 states; helped pass the Virginia Graeme Baker Pool & Spa Safety Act.",
     "url": "https://thezacfoundation.org/", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "20K+ children served.",
     "tags": ["water-safety", "foundation"], "verified": "2026-05"},
    {"id": "lts-020", "category": "learn_to_swim",
     "name": "Pool Safely (CPSC)", "type": "Government Campaign",
     "audience": "Public",
     "description": "U.S. federal water-safety campaign per the Virginia Graeme Baker Pool & Spa Safety Act.",
     "url": "https://www.poolsafely.gov/", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Issued $2.5M+ in 2024 grants.",
     "tags": ["water-safety", "government"], "verified": "2026-05"},
    {"id": "lts-021", "category": "learn_to_swim",
     "name": "Abbey's Hope Charitable Foundation", "type": "Foundation",
     "audience": "Children/families",
     "description": "Drove passage of the VGB Act; runs the \"10,000 Life Jackets\" program.",
     "url": "https://abbeyshope.org/", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Minnesota-based.",
     "tags": ["water-safety", "foundation"], "verified": "2026-05"},
    {"id": "lts-022", "category": "learn_to_swim",
     "name": "Water Safety USA", "type": "Coalition",
     "audience": "National coordination",
     "description": "Maintains the U.S. National Water Safety Action Plan 2023–2032 (99 actions).",
     "url": "https://watersafetyusa.org/", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Multi-organization roundtable.",
     "tags": ["water-safety", "coalition"], "verified": "2026-05"},
    {"id": "lts-023", "category": "learn_to_swim",
     "name": "United States Lifesaving Association", "type": "Lifeguard Association",
     "audience": "Beach lifeguards",
     "description": "Sets U.S. national lifeguard standards; partners with NOAA on rip-current education.",
     "url": "https://www.usla.org/", "pricing": "mixed", "region": "USA", "language": "en",
     "year_founded": 1964, "status": "active", "notes": "",
     "tags": ["water-safety", "lifeguard"], "verified": "2026-05"},
    {"id": "lts-024", "category": "learn_to_swim",
     "name": "Surf Life Saving Australia", "type": "Lifesaving Body",
     "audience": "Beachgoers",
     "description": "314 clubs and 181K+ members; coastal drowning prevention since 1907.",
     "url": "https://sls.com.au/", "pricing": "mixed", "region": "Australia", "language": "en",
     "year_founded": 1907, "status": "active", "notes": "715K+ rescues since founding.",
     "tags": ["water-safety", "lifeguard"], "verified": "2026-05"},
    {"id": "lts-025", "category": "learn_to_swim",
     "name": "International Life Saving Federation", "type": "International Body",
     "audience": "International orgs",
     "description": "Global coordinating body for lifesaving organizations.",
     "url": "https://www.ilsf.org/", "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["water-safety", "lifeguard"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 3. TECHNIQUE & STROKE RESOURCES
# ---------------------------------------------------------------------------

TECHNIQUE: list[dict[str, Any]] = [
    {"id": "tech-001", "category": "technique",
     "name": "GoSwim", "type": "Video Library",
     "audience": "All; coaches",
     "description": "3,000+ technique videos featuring 60+ Olympians; USA Swimming partner since 2014.",
     "url": "https://www.goswim.tv", "pricing": "freemium", "region": "global", "language": "en",
     "year_founded": None, "status": "active",
     "notes": "Founded by Glenn Mills (1980 USA Olympian).",
     "tags": ["technique", "video"], "verified": "2026-05"},
    {"id": "tech-002", "category": "technique",
     "name": "Swim Smooth", "type": "Methodology + Coaching",
     "audience": "Adults, triathletes",
     "description": "\"Swim Types\" methodology; consultants to British Triathlon.",
     "url": "https://www.swimsmooth.com", "pricing": "mixed", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Founders Paul Newsome & Adam Young.",
     "tags": ["technique", "triathlon"], "verified": "2026-05"},
    {"id": "tech-003", "category": "technique",
     "name": "Swim Smooth GURU", "type": "Online Platform",
     "audience": "All",
     "description": "Online platform with tailored plans and Stroke Insights.",
     "url": "https://www.swimsmooth.guru/", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Apple Watch / Garmin integration.",
     "tags": ["technique", "platform"], "verified": "2026-05"},
    {"id": "tech-004", "category": "technique",
     "name": "Effortless Swimming", "type": "Coaching + Video",
     "audience": "Adults, triathletes",
     "description": "Stroke analysis, clinics, and membership program; 6,000+ alumni.",
     "url": "https://effortlessswimming.com", "pricing": "mixed", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Founded by Brenton Ford (Melbourne).",
     "tags": ["technique", "video", "triathlon"], "verified": "2026-05"},
    {"id": "tech-005", "category": "technique",
     "name": "MySwimPro", "type": "App + Plans",
     "audience": "All",
     "description": "#1 fitness swim app: AI Coach, structured plans, dryland.",
     "url": "https://www.myswimpro.com", "pricing": "freemium", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "2.5M+ users; Apple App of the Year 2016.",
     "tags": ["technique", "app", "ai"], "verified": "2026-05"},
    {"id": "tech-006", "category": "technique",
     "name": "U.S. Masters Swimming Resources", "type": "Resource Hub",
     "audience": "Adults / masters",
     "description": "Adult learn-to-swim, technique videos, and find-a-coach directory.",
     "url": "https://www.usms.org", "pricing": "mixed", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Member-based.",
     "tags": ["technique", "masters"], "verified": "2026-05"},
    {"id": "tech-007", "category": "technique",
     "name": "USA Swimming Athlete Resources", "type": "Resource Hub",
     "audience": "Age-group → elite",
     "description": "Athlete development pathway, technique articles, GoSwim partnership.",
     "url": "https://www.usaswimming.org", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["technique", "ngb"], "verified": "2026-05"},
    {"id": "tech-008", "category": "technique",
     "name": "The Race Club", "type": "Video + Camps",
     "audience": "Competitive, triathletes",
     "description": "Lane 2/3 video subscription plus camps in Florida and California.",
     "url": "https://theraceclub.com", "pricing": "mixed", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Gary Hall Jr. & Sr.",
     "tags": ["technique", "camps", "video"], "verified": "2026-05"},
    {"id": "tech-009", "category": "technique",
     "name": "Fitter and Faster Swim Tour", "type": "Clinic Series",
     "audience": "Age-group",
     "description": "1,000+ U.S. clinics annually with Olympian clinicians.",
     "url": "https://fitterandfaster.com", "pricing": "paid", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "200K+ alumni.",
     "tags": ["technique", "clinics"], "verified": "2026-05"},
    {"id": "tech-010", "category": "technique",
     "name": "Skills N' Talents", "type": "Video + Camps",
     "audience": "All",
     "description": "Coverage of all four strokes plus dryland; international camps.",
     "url": "https://skillswimming.com", "pricing": "mixed", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Uranga brothers.",
     "tags": ["technique", "video"], "verified": "2026-05"},
    {"id": "tech-011", "category": "technique",
     "name": "YourSwimLog (Olivier Poirier-Leroy)", "type": "Articles + Books",
     "audience": "Competitive, parents",
     "description": "1,100+ articles; books include Conquer the Pool.",
     "url": "https://www.yourswimlog.com", "pricing": "mixed", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Two-time Olympic Trials qualifier.",
     "tags": ["technique", "blog", "books"], "verified": "2026-05"},
    {"id": "tech-012", "category": "technique",
     "name": "Coach Andrew Sheaff", "type": "Coach Education",
     "audience": "Coaches",
     "description": "Constraints-led coaching consultancy; Routledge book published 2024.",
     "url": "https://www.coachandrewsheaff.com", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Former University of Virginia coach.",
     "tags": ["coaching", "education"], "verified": "2026-05"},
    {"id": "tech-013", "category": "technique",
     "name": "Swimming World Magazine - Technique", "type": "Magazine Articles",
     "audience": "All",
     "description": "Magazine since 1960 with regular technique features.",
     "url": "https://www.swimmingworldmagazine.com", "pricing": "mixed", "region": "global", "language": "en",
     "year_founded": 1960, "status": "active", "notes": "",
     "tags": ["technique", "magazine"], "verified": "2026-05"},
    {"id": "tech-014", "category": "technique",
     "name": "ASCA \"Lessons from the Legends\"", "type": "Video Series",
     "audience": "Coaches",
     "description": "Coach-education video archive on the ASCA YouTube channel.",
     "url": "https://swimmingcoach.org", "pricing": "paid", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "ASCA membership required.",
     "tags": ["coaching", "video"], "verified": "2026-05"},
]
