"""Data part 4: apps & swim technology + books."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 6. APPS & SWIM TECHNOLOGY
# ---------------------------------------------------------------------------

APPS: list[dict[str, Any]] = [
    {"id": "app-001", "category": "apps", "name": "MySwimPro",
     "type": "Workout App", "audience": "All",
     "description": "iOS/Android/Apple Watch/Garmin workout app.",
     "url": "https://www.myswimpro.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["app", "workouts"], "verified": "2026-05"},
    {"id": "app-002", "category": "apps", "name": "Swim.com",
     "type": "Tracker + Workouts", "audience": "All",
     "description": "Workout sync across Apple Watch / Garmin / Wear OS.",
     "url": "https://www.swim.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free with Premium tier.",
     "tags": ["app", "tracking"], "verified": "2026-05"},
    {"id": "app-003", "category": "apps", "name": "FORM Smart Swim 2 (Pro/LT)",
     "type": "AR Goggles", "audience": "All",
     "description": "Heads-up display showing pace/HR/stroke; HeadCoach AI.",
     "url": "https://www.formswim.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$149–$329 hardware plus $119/yr subscription.",
     "tags": ["wearable", "ar"], "verified": "2026-05"},
    {"id": "app-004", "category": "apps", "name": "Garmin Connect / Swim 2 / Forerunner / Fenix",
     "type": "Watches", "audience": "All",
     "description": "GPS swim tracking, heart rate, SWOLF metric.",
     "url": "https://www.garmin.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$249–$899 hardware.",
     "tags": ["wearable"], "verified": "2026-05"},
    {"id": "app-005", "category": "apps", "name": "Apple Watch + Apple Health",
     "type": "Smartwatch", "audience": "All",
     "description": "Native watchOS swim tracking.",
     "url": "https://www.apple.com/apple-watch/", "pricing": "paid",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Hardware purchase.",
     "tags": ["wearable"], "verified": "2026-05"},
    {"id": "app-006", "category": "apps", "name": "Strava",
     "type": "Tracker + Social", "audience": "All",
     "description": "Logs swim activity from connected devices; social features.",
     "url": "https://www.strava.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$79.99/yr Premium.",
     "tags": ["app", "social"], "verified": "2026-05"},
    {"id": "app-007", "category": "apps", "name": "Swimmo",
     "type": "Smart Swim Watch", "audience": "All",
     "description": "Vibration-feedback pace coach.",
     "url": "https://www.swimmo.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "~$199 hardware.",
     "tags": ["wearable"], "verified": "2026-05"},
    {"id": "app-008", "category": "apps", "name": "Speedo On (formerly Pace Club)",
     "type": "App", "audience": "All",
     "description": "Speedo's swim tracking app; status fragmented across regions.",
     "url": "https://www.speedousa.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Regional fragmentation.",
     "tags": ["app"], "verified": "2026-05"},
    {"id": "app-009", "category": "apps", "name": "OnForm",
     "type": "Video Analysis", "audience": "Coaches/athletes",
     "description": "Slow-motion plus chat; modern Coach's Eye replacement on iOS/Android.",
     "url": "https://onform.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$5/mo or $49/yr.",
     "tags": ["video-analysis", "app"], "verified": "2026-05"},
    {"id": "app-010", "category": "apps", "name": "Hudl Technique",
     "type": "Video Analysis", "audience": "Coaches/athletes",
     "description": "Slow-motion analysis with side-by-side comparison.",
     "url": "https://www.hudl.com/products/technique", "pricing": "paid",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "$9.99/mo Elite tier.",
     "tags": ["video-analysis", "app"], "verified": "2026-05"},
    {"id": "app-011", "category": "apps", "name": "Dartfish",
     "type": "Pro Video Analysis", "audience": "Federations / pros",
     "description": "Federation/Olympic-level video analysis suite.",
     "url": "https://www.dartfish.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$500–$2,000 license tiers.",
     "tags": ["video-analysis"], "verified": "2026-05"},
    {"id": "app-012", "category": "apps", "name": "TritonWear",
     "type": "Wearable Analytics", "audience": "Coaches/athletes",
     "description": "Cap-mounted IMU; live data to coach iPad.",
     "url": "https://www.tritonwear.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$149+/yr per athlete.",
     "tags": ["wearable", "analytics"], "verified": "2026-05"},
    {"id": "app-013", "category": "apps", "name": "Phlex Edge",
     "type": "Goggle Wearable", "audience": "Competitive",
     "description": "Heart-rate via temple plus AI stroke analytics.",
     "url": "https://phlexswim.com/products/edge", "pricing": "paid",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "$199–$299 hardware.",
     "tags": ["wearable", "analytics"], "verified": "2026-05"},
    {"id": "app-014", "category": "apps", "name": "Holoswim 2s/Pro/Go",
     "type": "AR Goggles", "audience": "All",
     "description": "Holographic heads-up display; no subscription required.",
     "url": "https://www.holoswim.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$199–$329 hardware.",
     "tags": ["wearable", "ar"], "verified": "2026-05"},
    {"id": "app-015", "category": "apps", "name": "Final Surge App",
     "type": "Training Delivery", "audience": "Coaches/athletes",
     "description": "iOS/Android/Web companion to Final Surge platform.",
     "url": "https://www.finalsurge.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free + $6.58/mo Premium.",
     "tags": ["training", "app"], "verified": "2026-05"},
    {"id": "app-016", "category": "apps", "name": "TeamUnify / SportsEngine Motion app",
     "type": "Club Management", "audience": "Clubs",
     "description": "Replaces OnDeck app; sunset of OnDeck on Dec 31, 2024.",
     "url": "https://www.teamunify.com/", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "OnDeck retired.",
     "tags": ["app", "club"], "verified": "2026-05"},
    {"id": "app-017", "category": "apps", "name": "USA Swimming App",
     "type": "Membership App", "audience": "USA-S members",
     "description": "Ticketing and livestream access for USA-S events.",
     "url": "https://www.usaswimming.org/", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free with USA-S membership.",
     "tags": ["app", "ngb"], "verified": "2026-05"},
    {"id": "app-018", "category": "apps", "name": "Coach's Eye",
     "type": "Video Analysis", "audience": "Coaches",
     "description": "Discontinued by TechSmith in 2020; replaced by OnForm.",
     "url": "https://onform.com/", "pricing": "varies", "region": "global",
     "language": "en", "year_founded": None, "status": "defunct",
     "notes": "Sunsetted 2020.",
     "tags": ["video-analysis", "defunct"], "verified": "2026-05"},
    {"id": "app-019", "category": "apps", "name": "FINIS Smart Goggle",
     "type": "Goggle Wearable", "audience": "All",
     "description": "Goggle hardware sunsetted Dec 31, 2025; companion app continues for existing devices.",
     "url": "https://www.finisswim.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "defunct",
     "notes": "Hardware retired late 2025.",
     "tags": ["wearable", "defunct"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 7. BOOKS ON SWIMMING
# ---------------------------------------------------------------------------

BOOKS: list[dict[str, Any]] = [
    {"id": "book-001", "category": "books", "name": "Swimming Fastest",
     "type": "Coaching/Science Book", "audience": "Coaches",
     "description": "Comprehensive coaching reference covering biomechanics and physiology.",
     "url": "https://us.humankinetics.com/products/swimming-fastest",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2003,
     "status": "active",
     "notes": "Author Ernest W. Maglischo. Publisher Human Kinetics. ISBN 978-0736031806.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-002", "category": "books", "name": "Swimming Even Faster",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Predecessor to Swimming Fastest with substantial coaching detail.",
     "url": "https://www.amazon.com/Swimming-Even-Faster-Ernest-Maglischo/dp/1559340363",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 1993,
     "status": "active",
     "notes": "Author Ernest W. Maglischo. Publisher Mayfield. ISBN 978-1559340366.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-003", "category": "books", "name": "The Swim Coaching Bible Vol. I",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Anthology of coaching wisdom from elite practitioners.",
     "url": "https://us.humankinetics.com/products/the-swim-coaching-bible",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2001,
     "status": "active",
     "notes": "Editors Hannula & Thornton. ISBN 978-0736036467.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-004", "category": "books", "name": "The Swim Coaching Bible Vol. II",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Second volume with new contributors and modern approaches.",
     "url": "https://us.humankinetics.com/products/the-swim-coaching-bible-volume-ii",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2012,
     "status": "active",
     "notes": "Editors Hannula & Thornton. Human Kinetics.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-005", "category": "books", "name": "The Swimming Drill Book",
     "type": "Drill Reference", "audience": "Coaches/swimmers",
     "description": "Comprehensive catalog of stroke drills.",
     "url": "https://us.humankinetics.com/products/the-swimming-drill-book",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2007,
     "status": "active",
     "notes": "Author Ruben Guzman. ISBN 978-0736062510.",
     "tags": ["book", "drills"], "verified": "2026-05"},
    {"id": "book-006", "category": "books", "name": "Total Immersion",
     "type": "Adult/Technique Book", "audience": "Adult learners",
     "description": "Adult-focused efficient-swimming methodology.",
     "url": "https://www.totalimmersion.net/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": 1996, "status": "active",
     "notes": "Author Terry Laughlin. Publisher Touchstone. ISBN 978-0743253437.",
     "tags": ["book", "adults", "technique"], "verified": "2026-05"},
    {"id": "book-007", "category": "books", "name": "Championship Swim Training",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Periodization and training systems from a national-team coach.",
     "url": "https://us.humankinetics.com/products/championship-swim-training",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2003,
     "status": "active",
     "notes": "Authors Sweetenham & Atkinson. ISBN 978-0736045438.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-008", "category": "books", "name": "Swimming Anatomy",
     "type": "Anatomy Book", "audience": "Athletes/coaches",
     "description": "Stroke-specific anatomical analysis with strength training.",
     "url": "https://us.humankinetics.com/products/swimming-anatomy",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2009,
     "status": "active",
     "notes": "Author Ian McLeod. ISBN 978-0736075718.",
     "tags": ["book", "anatomy"], "verified": "2026-05"},
    {"id": "book-009", "category": "books", "name": "The Science of Winning",
     "type": "Physiology Book", "audience": "Coaches/scientists",
     "description": "Pioneering work on lactate-based training systems.",
     "url": "https://www.scienceofwinning.org/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": 2000, "status": "active",
     "notes": "Author Jan Olbrecht. Self-published.",
     "tags": ["book", "science"], "verified": "2026-05"},
    {"id": "book-010", "category": "books", "name": "Beneath the Surface: My Story",
     "type": "Memoir", "audience": "General readers",
     "description": "Memoir of Olympic gold medalist Michael Phelps.",
     "url": "https://www.skyhorsepublishing.com/9781683580874/beneath-the-surface/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2004,
     "status": "active",
     "notes": "Author Michael Phelps. Publisher Skyhorse. ISBN 978-1683580874.",
     "tags": ["book", "memoir"], "verified": "2026-05"},
    {"id": "book-011", "category": "books", "name": "The Golden Rules",
     "type": "Mindset Book", "audience": "General",
     "description": "Coaching mindset book from Phelps' longtime coach.",
     "url": "https://us.macmillan.com/books/9781250059505/thegoldenrules",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2016,
     "status": "active",
     "notes": "Author Bob Bowman. Publisher St. Martin's Press. ISBN 978-1250059505.",
     "tags": ["book", "mindset"], "verified": "2026-05"},
    {"id": "book-012", "category": "books", "name": "No Limits",
     "type": "Memoir", "audience": "General",
     "description": "Phelps' memoir following the 2008 Beijing Olympics.",
     "url": "https://www.simonandschuster.com/books/No-Limits/Michael-Phelps/9781439130728",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2008,
     "status": "active",
     "notes": "Author Michael Phelps. Publisher Free Press. ISBN 978-1439130728.",
     "tags": ["book", "memoir"], "verified": "2026-05"},
    {"id": "book-013", "category": "books", "name": "Just Add Water",
     "type": "Memoir", "audience": "General",
     "description": "Memoir of the most decorated female swimmer in history.",
     "url": "https://www.simonandschuster.com/books/Just-Add-Water/Katie-Ledecky/9781668060209",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2024,
     "status": "active",
     "notes": "Author Katie Ledecky. Publisher Simon & Schuster. ISBN 978-1668060209.",
     "tags": ["book", "memoir"], "verified": "2026-05"},
    {"id": "book-014", "category": "books", "name": "Open Water Swimming Manual",
     "type": "Open Water Book", "audience": "Open-water swimmers",
     "description": "Comprehensive guide to safe and effective open-water swimming.",
     "url": "https://www.penguinrandomhouse.com/books/220796/open-water-swimming-manual-by-lynne-cox/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2013,
     "status": "active",
     "notes": "Author Lynne Cox. Publisher Knopf. ISBN 978-0345806093.",
     "tags": ["book", "open-water"], "verified": "2026-05"},
    {"id": "book-015", "category": "books", "name": "Swimming to Antarctica",
     "type": "Memoir", "audience": "General",
     "description": "Memoir of long-distance ice swimming pioneer.",
     "url": "https://www.penguinrandomhouse.com/books/91960/swimming-to-antarctica-by-lynne-cox/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2004,
     "status": "active",
     "notes": "Author Lynne Cox. Publisher Knopf. ISBN 978-0156031301.",
     "tags": ["book", "memoir", "open-water"], "verified": "2026-05"},
    {"id": "book-016", "category": "books", "name": "Run, Swim, Throw, Cheat",
     "type": "Sports Science Book", "audience": "General",
     "description": "Sports science of human performance including swimming.",
     "url": "https://global.oup.com/academic/product/run-swim-throw-cheat-9780199678785",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2012,
     "status": "active",
     "notes": "Author Chris Cooper. Publisher Oxford UP. ISBN 978-0199678785.",
     "tags": ["book", "science"], "verified": "2026-05"},
    {"id": "book-017", "category": "books", "name": "Swim Smooth: The Complete Coaching System",
     "type": "Adult/Tri Coaching Book", "audience": "Coaches/swimmers",
     "description": "Complete book companion to the Swim Smooth methodology.",
     "url": "https://www.wiley.com/en-us/Swim+Smooth-p-9781119963196",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2012,
     "status": "active",
     "notes": "Authors Newsome & Young. Publisher Wiley. ISBN 978-1119963196.",
     "tags": ["book", "technique"], "verified": "2026-05"},
    {"id": "book-018", "category": "books", "name": "Breakthrough Swimming",
     "type": "Science/History Book", "audience": "Coaches/historians",
     "description": "History and science of swimming breakthroughs.",
     "url": "https://us.humankinetics.com/products/breakthrough-swimming",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2002,
     "status": "active",
     "notes": "Author Cecil Colwin. ISBN 978-0736037778.",
     "tags": ["book", "history"], "verified": "2026-05"},
    {"id": "book-019", "category": "books", "name": "Swimming Dynamics",
     "type": "Science Book", "audience": "Coaches",
     "description": "Hydrodynamic principles applied to stroke design.",
     "url": "https://www.amazon.com/Swimming-Dynamics-Winning-Techniques-Training/dp/1570281483",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 1999,
     "status": "active",
     "notes": "Author Cecil Colwin. ISBN 978-1570281488.",
     "tags": ["book", "science"], "verified": "2026-05"},
    {"id": "book-020", "category": "books", "name": "Swim Speed Secrets",
     "type": "Technique Book", "audience": "Triathletes",
     "description": "Sprint freestyle technique from Olympic gold medalist.",
     "url": "https://www.velopress.com/books/swim-speed-secrets/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2012,
     "status": "active",
     "notes": "Author Sheila Taormina. ISBN 978-1937715816.",
     "tags": ["book", "technique"], "verified": "2026-05"},
    {"id": "book-021", "category": "books", "name": "Swim Speed Strokes",
     "type": "Technique Book", "audience": "All",
     "description": "All four strokes for competitive swimmers.",
     "url": "https://www.velopress.com/books/swim-speed-strokes/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2014,
     "status": "active",
     "notes": "Author Sheila Taormina. ISBN 978-1937715212.",
     "tags": ["book", "technique"], "verified": "2026-05"},
    {"id": "book-022", "category": "books", "name": "Swim Speed Workouts",
     "type": "Training Book", "audience": "Triathletes",
     "description": "Training plans complementing the Speed Secrets methodology.",
     "url": "https://www.velopress.com/books/swim-speed-workouts/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2013,
     "status": "active",
     "notes": "Author Sheila Taormina. ISBN 978-1937715014.",
     "tags": ["book", "training"], "verified": "2026-05"},
    {"id": "book-023", "category": "books", "name": "Why We Swim",
     "type": "Cultural Book", "audience": "General",
     "description": "Cultural history and meaning of swimming.",
     "url": "https://algonquinbooks.com/titles/why-we-swim/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2020,
     "status": "active",
     "notes": "Author Bonnie Tsui. Publisher Algonquin. ISBN 978-1616207861.",
     "tags": ["book", "culture"], "verified": "2026-05"},
    {"id": "book-024", "category": "books", "name": "Swim: Why We Love the Water",
     "type": "Cultural Book", "audience": "General",
     "description": "Journalist's exploration of swimming's cultural place.",
     "url": "https://www.publicaffairsbooks.com/titles/lynn-sherr/swim/9781610390460/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2012,
     "status": "active",
     "notes": "Author Lynn Sherr. Publisher PublicAffairs. ISBN 978-1610390460.",
     "tags": ["book", "culture"], "verified": "2026-05"},
    {"id": "book-025", "category": "books", "name": "Haunts of the Black Masseur",
     "type": "History Book", "audience": "General",
     "description": "Cultural history of swimming through art and literature.",
     "url": "https://www.upress.umn.edu/9780816678754/haunts-of-the-black-masseur/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 1992,
     "status": "active",
     "notes": "Author Charles Sprawson. ISBN 978-0140235463.",
     "tags": ["book", "history"], "verified": "2026-05"},
    {"id": "book-026", "category": "books", "name": "Gold in the Water",
     "type": "Narrative Book", "audience": "General",
     "description": "Inside-look narrative of an Olympic training group.",
     "url": "https://us.macmillan.com/books/9780312311162/goldinthewater",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2001,
     "status": "active",
     "notes": "Author P. H. Mullen. Publisher St. Martin's. ISBN 978-0312311162.",
     "tags": ["book", "narrative"], "verified": "2026-05"},
    {"id": "book-027", "category": "books", "name": "Coaching Swimming Successfully",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Foundational coaching reference now in second edition.",
     "url": "https://us.humankinetics.com/products/coaching-swimming-successfully",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2003,
     "status": "active",
     "notes": "Author Dick Hannula. 2nd edition. ISBN 978-0736046176.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-028", "category": "books", "name": "Science of Swimming",
     "type": "Science Book", "audience": "All",
     "description": "Modern science of swimming performance.",
     "url": "https://www.dk.com/us/book/9780593844328-science-of-swimming/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2024,
     "status": "active",
     "notes": "Author Brett Hawke. Publisher DK. ISBN 978-0593844328.",
     "tags": ["book", "science"], "verified": "2026-05"},
    {"id": "book-029", "category": "books", "name": "The Three-Year Swim Club",
     "type": "History Book", "audience": "General",
     "description": "Story of Hawaii's underdog 1930s swim team.",
     "url": "https://www.hachettebookgroup.com/titles/julie-checkoway/the-three-year-swim-club/9781455523450/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2015,
     "status": "active",
     "notes": "Author Julie Checkoway. Publisher Grand Central. ISBN 978-1455523450.",
     "tags": ["book", "history"], "verified": "2026-05"},
    {"id": "book-030", "category": "books", "name": "Waterlog",
     "type": "Wild Swimming Book", "audience": "General",
     "description": "Classic narrative of wild swimming across Britain.",
     "url": "https://www.penguin.co.uk/books/55196/waterlog-by-roger-deakin/9780099282556",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 1999,
     "status": "active",
     "notes": "Author Roger Deakin. Publisher Vintage. ISBN 978-0099282556.",
     "tags": ["book", "open-water"], "verified": "2026-05"},
    {"id": "book-031", "category": "books", "name": "Relentless Spirit",
     "type": "Memoir", "audience": "General",
     "description": "Memoir of Olympic gold medalist Missy Franklin and family.",
     "url": "https://www.penguinrandomhouse.com/books/535143/relentless-spirit-by-missy-franklin-dick-franklin-and-dapaige-franklin-with-daniel-paisner/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2016,
     "status": "active",
     "notes": "Authors Missy Franklin et al. Publisher Dutton. ISBN 978-1101984253.",
     "tags": ["book", "memoir"], "verified": "2026-05"},
    {"id": "book-032", "category": "books", "name": "Age Is Just a Number",
     "type": "Memoir", "audience": "General",
     "description": "Memoir of five-time Olympian Dara Torres.",
     "url": "https://www.penguinrandomhouse.com/books/176091/age-is-just-a-number-by-dara-torres-with-elizabeth-weil/",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2009,
     "status": "active",
     "notes": "Author Dara Torres. Publisher Broadway. ISBN 978-0767931502.",
     "tags": ["book", "memoir"], "verified": "2026-05"},
    {"id": "book-033", "category": "books", "name": "A Constraints-Led Approach to Swim Coaching",
     "type": "Coaching Book", "audience": "Coaches",
     "description": "Modern scholarly application of constraints-led methodology to swimming.",
     "url": "https://www.routledge.com/9781032318899",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2024,
     "status": "active",
     "notes": "Authors Renshaw, Thompson, Hibbert, Mark, Chow. Publisher Routledge.",
     "tags": ["book", "coaching"], "verified": "2026-05"},
    {"id": "book-034", "category": "books", "name": "Swimming Science",
     "type": "Science Book", "audience": "Coaches/scientists",
     "description": "Edited volume on swimming science.",
     "url": "https://press.uchicago.edu/ucp/books/book/distributed/S/bo30688290.html",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": 2018,
     "status": "active",
     "notes": "Editor G. John Mullen. Publisher U. of Chicago / ICB. ISBN 978-0226385143.",
     "tags": ["book", "science"], "verified": "2026-05"},
]
