"""Data part 5: certifications & sports science."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 8. COACHING CERTIFICATIONS
# ---------------------------------------------------------------------------

CERTIFICATIONS: list[dict[str, Any]] = [
    {"id": "cert-001", "category": "certifications",
     "name": "ASCA Levels 1–5", "type": "Coaching Certification",
     "audience": "Coaches",
     "description": "American Swimming Coaches Association tiered certification (1 entry → 5 Olympic).",
     "url": "https://swimmingcoach.org/page/certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "ASCA membership required.",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-002", "category": "certifications",
     "name": "USA Swimming Coach Certification (Core/ADM)", "type": "Coaching Certification",
     "audience": "All US club coaches",
     "description": "Mandatory USA Swimming coaching certification with ADM modules.",
     "url": "https://www.usaswimming.org/coaches-leaders/coaches/coach-certification-program",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active",
     "notes": "Membership and background check required (~$36.50).",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-003", "category": "certifications",
     "name": "USA Swimming STSC (Safety Training)", "type": "Safety Certification",
     "audience": "Coaches",
     "description": "Mandatory Safety Training for Swim Coaches (USA-S / Red Cross).",
     "url": "https://www.usaswimming.org/coaches-leaders/coaches/coach-safety-requirements",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "safety"], "verified": "2026-05"},
    {"id": "cert-004", "category": "certifications",
     "name": "U.S. Paralympics Swimming PSCC L1–3", "type": "Para Coach Certification",
     "audience": "Para coaches",
     "description": "Tiered Para Swim Coach Certification under USOPC.",
     "url": "https://www.usparaswimming.org/coaching-certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "Tiered.",
     "tags": ["certification", "para"], "verified": "2026-05"},
    {"id": "cert-005", "category": "certifications",
     "name": "Swim England Assistant Coach (Level 1)", "type": "Coaching Qualification",
     "audience": "Entry-level",
     "description": "Entry-level Institute of Swimming coaching qualification.",
     "url": "https://instituteofswimming.org/", "pricing": "paid", "region": "England",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "~£390.",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-006", "category": "certifications",
     "name": "Swim England Coach (Level 2)", "type": "Coaching Qualification",
     "audience": "Independent coach",
     "description": "Level 2 qualification permitting independent coaching.",
     "url": "https://instituteofswimming.org/course-information/swim-england-swimming-coach",
     "pricing": "paid", "region": "England", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-007", "category": "certifications",
     "name": "Swim England Senior Coach (Level 3)", "type": "Coaching Qualification",
     "audience": "Senior coach",
     "description": "Year-long mentored Level 3 senior coaching qualification.",
     "url": "https://www.swimming.org/sport/swimming-coaching/",
     "pricing": "paid", "region": "England", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-008", "category": "certifications",
     "name": "USMS ALTS Instructor", "type": "Adult LTS Certification",
     "audience": "Adult LTS instructor",
     "description": "Adult Learn-to-Swim instructor certification from USMS.",
     "url": "https://www.usms.org/alts-central/alts-instructor-certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "USMS membership required.",
     "tags": ["certification", "lts"], "verified": "2026-05"},
    {"id": "cert-009", "category": "certifications",
     "name": "USMS Coach Certification L1–4", "type": "Masters Coaching Certification",
     "audience": "Masters coach",
     "description": "Tiered USMS coach certification for masters programs.",
     "url": "https://www.usms.org/coach-central/coach-certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "masters"], "verified": "2026-05"},
    {"id": "cert-010", "category": "certifications",
     "name": "World Aquatics Coach Certification L1–3", "type": "Coaching Certification",
     "audience": "National → World",
     "description": "Tiered international coaching credential.",
     "url": "https://www.worldaquatics.com/development/programmes/Athletes-Entourage",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "Course free; certification fee $30.",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-011", "category": "certifications",
     "name": "ISCA Bronze/Silver Shield", "type": "Coaching Recognition",
     "audience": "Coaches",
     "description": "International Swim Coaches Association tiered shields.",
     "url": "https://swimisca.org/services/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$75/yr plus course fees.",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-012", "category": "certifications",
     "name": "STA Level 2", "type": "Teacher Qualification",
     "audience": "Independent teacher",
     "description": "Swimming Teachers Association independent teacher qualification (UK).",
     "url": "https://www.sta.co.uk/sta-level-2-swimming-teacher-qualification/",
     "pricing": "paid", "region": "UK", "language": "en", "year_founded": None,
     "status": "active", "notes": "~£795.",
     "tags": ["certification", "teaching"], "verified": "2026-05"},
    {"id": "cert-013", "category": "certifications",
     "name": "Australian Swim Coach Course (ASCC)", "type": "Coaching Certification",
     "audience": "Australian coaches",
     "description": "Foundation-to-accredited coaching pathway.",
     "url": "https://swim.org.au/", "pricing": "paid", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-014", "category": "certifications",
     "name": "AUSTSWIM Teacher of Swimming & Water Safety", "type": "Teaching Certification",
     "audience": "Entry-level teacher",
     "description": "Entry-level swim teaching qualification in Australia.",
     "url": "https://austswim.com.au/", "pricing": "paid", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["certification", "teaching"], "verified": "2026-05"},
    {"id": "cert-015", "category": "certifications",
     "name": "American Red Cross Lifeguarding (r.24)", "type": "Lifeguard Certification",
     "audience": "15+",
     "description": "Standard American Red Cross lifeguard certification (r.24 revision).",
     "url": "https://www.redcross.org/take-a-class/lifeguarding",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "$250–$400.",
     "tags": ["certification", "lifeguard"], "verified": "2026-05"},
    {"id": "cert-016", "category": "certifications",
     "name": "American Red Cross Water Safety Instructor (WSI)", "type": "Instructor Certification",
     "audience": "Swim instructor (16+)",
     "description": "Foundational U.S. swim instructor certification.",
     "url": "https://www.redcross.org/take-a-class/swimming/water-safety/water-safety-instructor-certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "instructor"], "verified": "2026-05"},
    {"id": "cert-017", "category": "certifications",
     "name": "YMCA Lifeguard", "type": "Lifeguard Certification",
     "audience": "15+",
     "description": "YMCA lifeguard certification recognized at Y facilities.",
     "url": "https://www.ymca.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Pricing varies.",
     "tags": ["certification", "lifeguard"], "verified": "2026-05"},
    {"id": "cert-018", "category": "certifications",
     "name": "Ellis & Associates ILTP", "type": "Lifeguard Licensing",
     "audience": "Lifeguard license",
     "description": "Facility-based International Lifeguard Training Program.",
     "url": "https://jellis.com/services/lifeguard-certification",
     "pricing": "paid", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "Facility-based.",
     "tags": ["certification", "lifeguard"], "verified": "2026-05"},
    {"id": "cert-019", "category": "certifications",
     "name": "StarGuard ELITE", "type": "Lifeguard Certification",
     "audience": "Lifeguard",
     "description": "Aquatic risk-management lifeguard certification.",
     "url": "https://www.starguardelite.com/", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["certification", "lifeguard"], "verified": "2026-05"},
    {"id": "cert-020", "category": "certifications",
     "name": "RLSS NPLQ", "type": "Lifeguard Qualification",
     "audience": "UK pool lifeguards",
     "description": "National Pool Lifeguard Qualification (UK).",
     "url": "https://www.rlss.org.uk/pages/category/lifeguard-courses",
     "pricing": "paid", "region": "UK", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "lifeguard"], "verified": "2026-05"},
    {"id": "cert-021", "category": "certifications",
     "name": "NCCP Swimming (Community → Senior)", "type": "Coaching Certification",
     "audience": "All coach levels",
     "description": "Canadian National Coaching Certification Program for swimming.",
     "url": "https://www.swimming.ca/national-coaching-certification-program-nccp/",
     "pricing": "paid", "region": "Canada", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
    {"id": "cert-022", "category": "certifications",
     "name": "WOWSA Open Water Coaching L1–5", "type": "Coaching Certification",
     "audience": "Open-water coaches",
     "description": "World Open Water Swimming Association tiered open-water credential.",
     "url": "https://www.openwaterswimming.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["certification", "open-water"], "verified": "2026-05"},
    {"id": "cert-023", "category": "certifications",
     "name": "WSCA Professional Swim Coaches Course", "type": "Coaching Certification",
     "audience": "All",
     "description": "World Swimming Coaches Association professional course.",
     "url": "https://www.wscacoach.org/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$50–$95 entry tiers.",
     "tags": ["certification", "coaching"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 9. SPORTS SCIENCE, BIOMECHANICS & RESEARCH
# ---------------------------------------------------------------------------

SCIENCE: list[dict[str, Any]] = [
    {"id": "sci-001", "category": "science",
     "name": "BMS - Biomechanics & Medicine in Swimming Symposium", "type": "Conference",
     "audience": "Researchers",
     "description": "Quadrennial international symposium; foundational venue for swim science.",
     "url": "https://bms.sport-iat.de/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "XV BMS in 2026: https://www.bms2026.com.br/",
     "tags": ["science", "conference"], "verified": "2026-05"},
    {"id": "sci-002", "category": "science",
     "name": "Journal of Swimming Research (ASCA)", "type": "Peer-reviewed Journal",
     "audience": "Coaches/researchers",
     "description": "ASCA's peer-reviewed swimming journal with open archive.",
     "url": "https://swimmingcoach.org/page/JSR", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free archive.",
     "tags": ["science", "journal"], "verified": "2026-05"},
    {"id": "sci-003", "category": "science",
     "name": "PubMed", "type": "Research Database",
     "audience": "Researchers",
     "description": "U.S. National Library of Medicine biomedical research database.",
     "url": "https://pubmed.ncbi.nlm.nih.gov", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "database"], "verified": "2026-05"},
    {"id": "sci-004", "category": "science",
     "name": "Swimming Science Bulletin (Brent Rushall, SDSU)", "type": "Archive",
     "audience": "Coaches/researchers",
     "description": "Long-running archive of swimming science briefs.",
     "url": "https://coachsci.sdsu.edu/swim/bullets/table.htm",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["science", "archive"], "verified": "2026-05"},
    {"id": "sci-005", "category": "science",
     "name": "International Journal of Aquatic Research and Education (IJARE)", "type": "Open-access Journal",
     "audience": "Researchers",
     "description": "Open-access journal covering aquatic research and education.",
     "url": "https://scholarworks.bgsu.edu/ijare/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "journal"], "verified": "2026-05"},
    {"id": "sci-006", "category": "science",
     "name": "Journal of Strength and Conditioning Research", "type": "Peer-reviewed Journal",
     "audience": "Researchers",
     "description": "NSCA-affiliated S&C journal with regular swimming articles.",
     "url": "https://journals.lww.com/nsca-jscr", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Subscription.",
     "tags": ["science", "journal"], "verified": "2026-05"},
    {"id": "sci-007", "category": "science",
     "name": "Journal of Sports Sciences", "type": "Peer-reviewed Journal",
     "audience": "Researchers",
     "description": "Multidisciplinary sport science journal.",
     "url": "https://www.tandfonline.com/journals/rjsp20",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "Subscription.",
     "tags": ["science", "journal"], "verified": "2026-05"},
    {"id": "sci-008", "category": "science",
     "name": "Swimming Science (G. John Mullen)", "type": "Blog/Resources",
     "audience": "Coaches/athletes",
     "description": "Practitioner-focused blog covering training, recovery, and rehab.",
     "url": "https://www.swimmingscience.net/", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "blog"], "verified": "2026-05"},
    {"id": "sci-009", "category": "science",
     "name": "USA Swimming Race Analysis", "type": "Reports",
     "audience": "Coaches/athletes",
     "description": "USA-S race analysis from major championship meets.",
     "url": "https://swims.usaswimming.org/SWIMSHelp/About_Race_Analysis.htm",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["science", "data"], "verified": "2026-05"},
    {"id": "sci-010", "category": "science",
     "name": "Swim England Race Analysis", "type": "Reports",
     "audience": "Coaches/athletes",
     "description": "Swim England race-analysis reports from elite competition.",
     "url": "https://www.swimming.org/swimengland/", "pricing": "free",
     "region": "England", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["science", "data"], "verified": "2026-05"},
    {"id": "sci-011", "category": "science",
     "name": "INSEP", "type": "National Sport Institute",
     "audience": "Elite athletes / researchers",
     "description": "Institut national du sport, de l'expertise et de la performance (France).",
     "url": "https://www.insep.fr", "pricing": "free", "region": "France",
     "language": "fr", "year_founded": None, "status": "active",
     "notes": "Free informational content.",
     "tags": ["science", "institute"], "verified": "2026-05"},
    {"id": "sci-012", "category": "science",
     "name": "Australian Institute of Sport", "type": "National Sport Institute",
     "audience": "Elite athletes / researchers",
     "description": "Australia's national sport institute.",
     "url": "https://www.ais.gov.au", "pricing": "free", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "institute"], "verified": "2026-05"},
    {"id": "sci-013", "category": "science",
     "name": "UK Sports Institute", "type": "National Sport Institute",
     "audience": "Elite athletes / researchers",
     "description": "UK Sports Institute swimming profile (rebranded April 2023).",
     "url": "https://uksportsinstitute.co.uk/profile/swimming/",
     "pricing": "free", "region": "UK", "language": "en", "year_founded": None,
     "status": "rebranded", "notes": "Formerly English Institute of Sport.",
     "tags": ["science", "institute"], "verified": "2026-05"},
    {"id": "sci-014", "category": "science",
     "name": "World Aquatics Knowledge Hub", "type": "Federation Resource",
     "audience": "All",
     "description": "World Aquatics' resource library for athletes, coaches, and federations.",
     "url": "https://www.worldaquatics.com/development/aquatics-knowledge-hub",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["science", "federation"], "verified": "2026-05"},
    {"id": "sci-015", "category": "science",
     "name": "Olympic Studies Centre / IOC Library", "type": "Historical Archive",
     "audience": "Researchers",
     "description": "Olympic historical research and library access.",
     "url": "https://library.olympics.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["history", "archive"], "verified": "2026-05"},
    {"id": "sci-016", "category": "science",
     "name": "Sports Performance Bulletin", "type": "Practitioner Magazine",
     "audience": "Coaches/athletes",
     "description": "Applied sport science practitioner magazine.",
     "url": "https://www.sportsperformancebulletin.com",
     "pricing": "paid", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "Subscription.",
     "tags": ["science", "magazine"], "verified": "2026-05"},
    {"id": "sci-017", "category": "science",
     "name": "ResearchGate", "type": "Academic Network",
     "audience": "Researchers",
     "description": "Academic networking platform with researcher-shared papers.",
     "url": "https://www.researchgate.net", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "network"], "verified": "2026-05"},
    {"id": "sci-018", "category": "science",
     "name": "Google Scholar", "type": "Search Engine",
     "audience": "All",
     "description": "Academic search engine for published research.",
     "url": "https://scholar.google.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "search"], "verified": "2026-05"},
    {"id": "sci-019", "category": "science",
     "name": "The Sport Journal (USSA)", "type": "Open-access Journal",
     "audience": "Researchers",
     "description": "Open-access journal of the United States Sports Academy.",
     "url": "https://thesportjournal.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["science", "journal"], "verified": "2026-05"},
]
