"""Data part 3: YouTube channels & training plans."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 4. YOUTUBE CHANNELS
# ---------------------------------------------------------------------------

YOUTUBE: list[dict[str, Any]] = [
    {"id": "yt-001", "category": "youtube", "name": "Effortless Swimming",
     "type": "YouTube Channel", "audience": "Adults, triathletes",
     "description": "Adult freestyle and triathlon technique tutorials.",
     "url": "https://www.youtube.com/@EffortlessSwimming", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~422K subscribers (2026-05).",
     "tags": ["youtube", "technique"], "verified": "2026-05"},
    {"id": "yt-002", "category": "youtube", "name": "Skills N' Talents",
     "type": "YouTube Channel", "audience": "All",
     "description": "All-stroke tutorials plus dryland content.",
     "url": "https://www.youtube.com/channel/UC8wwEsUeTG9cpzvWT5Dsdqw",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "~986K subscribers.",
     "tags": ["youtube", "technique"], "verified": "2026-05"},
    {"id": "yt-003", "category": "youtube", "name": "MySwimPro",
     "type": "YouTube Channel", "audience": "All",
     "description": "Workouts, technique, and training tips.",
     "url": "https://www.youtube.com/@MySwimPro", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~400K subscribers.",
     "tags": ["youtube", "training"], "verified": "2026-05"},
    {"id": "yt-004", "category": "youtube", "name": "Fares Ksebati",
     "type": "YouTube Channel", "audience": "Adults",
     "description": "Personal channel of MySwimPro CEO; lifestyle and tips.",
     "url": "https://www.youtube.com/channel/UChaZYqHG3YPWIHHDmZI7lDw",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "~1M subscribers.",
     "tags": ["youtube"], "verified": "2026-05"},
    {"id": "yt-005", "category": "youtube", "name": "GoSwim",
     "type": "YouTube Channel", "audience": "All",
     "description": "Drills and detailed technique breakdowns.",
     "url": "https://www.youtube.com/@GoSwimTV", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~156K subscribers.",
     "tags": ["youtube", "drills"], "verified": "2026-05"},
    {"id": "yt-006", "category": "youtube", "name": "The Race Club",
     "type": "YouTube Channel", "audience": "Competitive",
     "description": "Underwater technique analysis with Gary Hall Sr.",
     "url": "https://www.youtube.com/@theraceclub", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~300K subscribers.",
     "tags": ["youtube", "technique"], "verified": "2026-05"},
    {"id": "yt-007", "category": "youtube", "name": "Swim Smooth",
     "type": "YouTube Channel", "audience": "Adults, triathletes",
     "description": "Methodology demonstrations.",
     "url": "https://www.youtube.com/@swimsmooth", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Smaller subscriber base than competitors.",
     "tags": ["youtube"], "verified": "2026-05"},
    {"id": "yt-008", "category": "youtube", "name": "USA Swimming",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Race videos and athlete content from USA Swimming.",
     "url": "https://www.youtube.com/@USASwimming", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "~185K subscribers.",
     "tags": ["youtube", "ngb"], "verified": "2026-05"},
    {"id": "yt-009", "category": "youtube", "name": "World Aquatics",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Race coverage and athlete features.",
     "url": "https://www.youtube.com/@WorldAquatics", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~431K subscribers.",
     "tags": ["youtube", "federation"], "verified": "2026-05"},
    {"id": "yt-010", "category": "youtube", "name": "SwimSwam",
     "type": "YouTube Channel", "audience": "Public",
     "description": "News and interviews from the SwimSwam team.",
     "url": "https://www.youtube.com/@swimswam", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~97K subscribers.",
     "tags": ["youtube", "news"], "verified": "2026-05"},
    {"id": "yt-011", "category": "youtube", "name": "Caeleb Dressel",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Pro technique vlogs from the Olympic gold medalist.",
     "url": "https://www.youtube.com/@CaelebDressel", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "~51K subscribers.",
     "tags": ["youtube", "vlog"], "verified": "2026-05"},
    {"id": "yt-012", "category": "youtube", "name": "Cody Miller",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Olympic medalist vlog channel.",
     "url": "https://www.youtube.com/@CodyMillerOlympicSwimmer", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "Large subscriber base.",
     "tags": ["youtube", "vlog"], "verified": "2026-05"},
    {"id": "yt-013", "category": "youtube", "name": "Michael Andrew Swimming",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Pro vlog from U.S. Olympian Michael Andrew.",
     "url": "https://www.youtube.com/@MichaelAndrewSwimming", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "~62K subscribers.",
     "tags": ["youtube", "vlog"], "verified": "2026-05"},
    {"id": "yt-014", "category": "youtube", "name": "Global Triathlon Network (GTN)",
     "type": "YouTube Channel", "audience": "Triathletes",
     "description": "Triathlon coverage including swim training.",
     "url": "https://www.youtube.com/@gtn", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~1.1M subscribers.",
     "tags": ["youtube", "triathlon"], "verified": "2026-05"},
    {"id": "yt-015", "category": "youtube", "name": "Triathlon Taren",
     "type": "YouTube Channel", "audience": "Triathletes",
     "description": "Triathlon training vlogs.",
     "url": "https://www.youtube.com/@TriathlonTaren", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~158–191K subscribers.",
     "tags": ["youtube", "triathlon"], "verified": "2026-05"},
    {"id": "yt-016", "category": "youtube", "name": "Chris Burton Swims",
     "type": "YouTube Channel", "audience": "Open-water swimmers",
     "description": "Open-water tips and tutorials.",
     "url": "https://www.youtube.com/c/ChrisBurtonSwims", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Smaller subscriber base.",
     "tags": ["youtube", "open-water"], "verified": "2026-05"},
    {"id": "yt-017", "category": "youtube", "name": "SWIMVICE (Mandy Bradley)",
     "type": "YouTube Channel", "audience": "All",
     "description": "Tutorials with focus on accessibility.",
     "url": "https://www.youtube.com/@SWIMVICE", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "~94K subscribers.",
     "tags": ["youtube", "tutorials"], "verified": "2026-05"},
    {"id": "yt-018", "category": "youtube", "name": "SwimUp (Evgeny Lomtev)",
     "type": "YouTube Channel", "audience": "Beginners",
     "description": "Beginner-focused tutorials.",
     "url": "https://www.youtube.com/@SwimUp", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Smaller subscriber base.",
     "tags": ["youtube", "beginners"], "verified": "2026-05"},
    {"id": "yt-019", "category": "youtube", "name": "Propulsion Swimming",
     "type": "YouTube Channel", "audience": "Public",
     "description": "British swimming news and technique features.",
     "url": "https://www.youtube.com/@PropulsionSwimming", "pricing": "free",
     "region": "GB", "language": "en", "year_founded": None, "status": "active",
     "notes": "~927K subscribers.",
     "tags": ["youtube", "news"], "verified": "2026-05"},
    {"id": "yt-020", "category": "youtube", "name": "Olivier Poirier-Leroy",
     "type": "YouTube Channel", "audience": "Competitive",
     "description": "High-performance tips for serious swimmers.",
     "url": "https://www.youtube.com/c/olivierpoirierleroy", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Smaller subscriber base.",
     "tags": ["youtube", "competitive"], "verified": "2026-05"},
    {"id": "yt-021", "category": "youtube", "name": "Andrew Sheaff",
     "type": "YouTube Channel", "audience": "Coaches",
     "description": "Coach-education content from a constraints-led perspective.",
     "url": "https://www.youtube.com/channel/UC7Ad8gZFwkCPaua8FVEzevw",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "Smaller subscriber base.",
     "tags": ["youtube", "coaching"], "verified": "2026-05"},
    {"id": "yt-022", "category": "youtube", "name": "British Swimming / Aquatics GB",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Performance highlights from GB athletes.",
     "url": "https://www.youtube.com/@BritishSwimming", "pricing": "free",
     "region": "GB", "language": "en", "year_founded": None, "status": "active",
     "notes": "~32K subscribers.",
     "tags": ["youtube", "ngb"], "verified": "2026-05"},
    {"id": "yt-023", "category": "youtube", "name": "Swimnerd",
     "type": "YouTube Channel", "audience": "Coaches, meet directors",
     "description": "Pace clocks, scoreboards, meet technology.",
     "url": "https://www.youtube.com/@swimnerd", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Niche.",
     "tags": ["youtube", "tech"], "verified": "2026-05"},
    {"id": "yt-024", "category": "youtube", "name": "Swim Channel",
     "type": "YouTube Channel", "audience": "Public",
     "description": "Swimming lifestyle content.",
     "url": "https://www.youtube.com/@swimchannel", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Niche.",
     "tags": ["youtube"], "verified": "2026-05"},
    {"id": "yt-025", "category": "youtube", "name": "ASCA",
     "type": "YouTube Channel", "audience": "Coaches",
     "description": "Coach-education videos from ASCA.",
     "url": "https://www.youtube.com/@ASCAcoach", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Niche.",
     "tags": ["youtube", "coaching"], "verified": "2026-05"},
    {"id": "yt-026", "category": "youtube", "name": "ISCA",
     "type": "YouTube Channel", "audience": "Coaches",
     "description": "Coach-education videos from ISCA.",
     "url": "https://www.youtube.com/@SwimISCA", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "Niche.",
     "tags": ["youtube", "coaching"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 5. TRAINING PLANS & WORKOUT REPOSITORIES
# ---------------------------------------------------------------------------

TRAINING_PLANS: list[dict[str, Any]] = [
    {"id": "train-001", "category": "training_plans",
     "name": "MySwimPro Workouts and Plans", "type": "App / Plans",
     "audience": "All",
     "description": "AI Swim Coach, structured plans, dryland routines.",
     "url": "https://www.myswimpro.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["training", "app"], "verified": "2026-05"},
    {"id": "train-002", "category": "training_plans",
     "name": "USA Swimming Coaching Resources", "type": "Resource Hub",
     "audience": "USA-S coaches",
     "description": "Daily, weekly, and seasonal planning templates.",
     "url": "https://www.usaswimming.org/coaches-leaders/coaching-resources",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "Free with USA-S membership.",
     "tags": ["training", "coaches"], "verified": "2026-05"},
    {"id": "train-003", "category": "training_plans",
     "name": "SwimSwam Workouts", "type": "Article Library",
     "audience": "All",
     "description": "Coach-submitted workout articles.",
     "url": "https://swimswam.com/category/workouts/", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["training", "workouts"], "verified": "2026-05"},
    {"id": "train-004", "category": "training_plans",
     "name": "U.S. Masters Swimming Workout Library", "type": "Workout Database",
     "audience": "Masters",
     "description": "Hundreds of workouts; integrates with Swim.com.",
     "url": "https://www.usms.org/workout-library", "pricing": "paid",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "USMS member-only.",
     "tags": ["training", "masters"], "verified": "2026-05"},
    {"id": "train-005", "category": "training_plans",
     "name": "Swim Smooth", "type": "Methodology + Plans",
     "audience": "All",
     "description": "Stroke-Type plans, clinics, and squad training.",
     "url": "https://www.swimsmooth.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["training", "methodology"], "verified": "2026-05"},
    {"id": "train-006", "category": "training_plans",
     "name": "TrainingPeaks", "type": "Platform",
     "audience": "Self-coached & coached",
     "description": "Plan marketplace and performance metrics.",
     "url": "https://www.trainingpeaks.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$19.99/mo Premium tier.",
     "tags": ["training", "platform"], "verified": "2026-05"},
    {"id": "train-007", "category": "training_plans",
     "name": "TriDot", "type": "Platform",
     "audience": "Triathletes",
     "description": "AI-driven triathlon training; IRONMAN partner.",
     "url": "https://www.tridot.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$14.99–$199 per month tiers.",
     "tags": ["training", "triathlon"], "verified": "2026-05"},
    {"id": "train-008", "category": "training_plans",
     "name": "Garmin Connect Swim Workouts", "type": "Platform",
     "audience": "Garmin users",
     "description": "Structured workouts; Connect IQ ecosystem.",
     "url": "https://connect.garmin.com/", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free with compatible Garmin device.",
     "tags": ["training", "wearable"], "verified": "2026-05"},
    {"id": "train-009", "category": "training_plans",
     "name": "Final Surge", "type": "Coaching Platform",
     "audience": "Coaches/athletes",
     "description": "Plan delivery and marketplace for coaches.",
     "url": "https://www.finalsurge.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Free + $6.58/mo Premium tier.",
     "tags": ["training", "platform"], "verified": "2026-05"},
    {"id": "train-010", "category": "training_plans",
     "name": "Commit Swimming", "type": "Coaching Platform",
     "audience": "Coaches/clubs",
     "description": "Plain-text workout parsing plus team management.",
     "url": "https://www.commitswimming.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "$8/mo and up.",
     "tags": ["training", "platform"], "verified": "2026-05"},
    {"id": "train-011", "category": "training_plans",
     "name": "Effortless Swimming Membership", "type": "Membership Program",
     "audience": "Adults, triathletes",
     "description": "8-Week Faster Freestyle, drill library, 5K/10K plans.",
     "url": "https://effortlessswimming.com/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["training", "membership"], "verified": "2026-05"},
    {"id": "train-012", "category": "training_plans",
     "name": "220 Triathlon Swim Training", "type": "Article Library",
     "audience": "Triathletes",
     "description": "Free 8-week plans and open-water preparation guides.",
     "url": "https://www.220triathlon.com/training/swim-training",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["training", "triathlon"], "verified": "2026-05"},
    {"id": "train-013", "category": "training_plans",
     "name": "TeamUnify / SportsEngine Motion", "type": "Club Management",
     "audience": "Clubs",
     "description": "Roster, billing, attendance, and workouts.",
     "url": "https://www.teamunify.com/", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Club-paid.",
     "tags": ["training", "club"], "verified": "2026-05"},
    {"id": "train-014", "category": "training_plans",
     "name": "GoSwim app", "type": "App",
     "audience": "All",
     "description": "Swim evaluator plus full video library.",
     "url": "https://www.goswim.tv/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Subscription.",
     "tags": ["training", "app", "video"], "verified": "2026-05"},
    {"id": "train-015", "category": "training_plans",
     "name": "Swim Coach App", "type": "App",
     "audience": "All",
     "description": "Personalized workouts; Apple Watch / Garmin support.",
     "url": "https://swimcoachapp.com/en/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["training", "app"], "verified": "2026-05"},
    {"id": "train-016", "category": "training_plans",
     "name": "Swimplan", "type": "Workout Generator",
     "audience": "Fitness/competitive",
     "description": "Workout generator with parameter controls.",
     "url": "https://swimplan.com/", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["training", "generator"], "verified": "2026-05"},
    {"id": "train-017", "category": "training_plans",
     "name": "SwimUp.io", "type": "App",
     "audience": "All",
     "description": "Tracker plus plans with in-app coach chat.",
     "url": "https://swimup.io/", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "Subscription.",
     "tags": ["training", "app"], "verified": "2026-05"},
    {"id": "train-018", "category": "training_plans",
     "name": "USA Swimming Dryland Resources", "type": "Resource Hub",
     "audience": "Coaches",
     "description": "Dryland safety guidelines and programming guides.",
     "url": "https://www.usaswimming.org/coaches-leaders", "pricing": "free",
     "region": "USA", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["training", "dryland"], "verified": "2026-05"},
    {"id": "train-019", "category": "training_plans",
     "name": "Beyond the Black Line (Australia)", "type": "Welfare Program",
     "audience": "Teen swimmers",
     "description": "Athlete wellbeing program for teen swimmers.",
     "url": "https://www.beyondtheblackline.com.au/", "pricing": "free",
     "region": "Australia", "language": "en", "year_founded": None, "status": "active",
     "notes": "Note: not a workout database despite older directory listings.",
     "tags": ["welfare", "youth"], "verified": "2026-05"},
]
