"""
Swimming Resources Database - source of truth.

All resource entries live here as Python dicts. The build script
(`scripts/build_dataset.py`) reads from this module and emits
JSON, JSONL, CSV, and Parquet artifacts plus the public README.

To contribute a resource: add a dict to the appropriate list below,
then run `python scripts/build_dataset.py` from the repo root.
URLs MUST be verified loadable; flag rebrands/defuncts via `status`.
"""

from __future__ import annotations
from typing import Any

# Schema reference (every resource dict should match this shape):
#   id            str   unique slug, "<category-prefix>-NNN"
#   category      str   one of CATEGORY_IDS
#   subcategory   str   optional finer grouping (e.g. "international")
#   name          str   display name
#   type          str   what it is (Federation, App, Book, etc.)
#   audience      str   who it serves (Beginners, All, Coaches, ...)
#   description   str   one-sentence summary
#   url           str   canonical URL
#   pricing       str   one of free | paid | freemium | mixed | varies
#   region        str   global | <continent> | <country>
#   language      str   ISO 639-1 primary language code (en, fr, de, ...)
#   year_founded  int|None
#   status        str   active | rebranded | defunct
#   notes         str   any caveats, rebrand info, ISBNs, etc.
#   tags          list[str]
#   verified      str   YYYY-MM date last checked

CATEGORY_IDS = [
    "governing_bodies", "learn_to_swim", "technique", "youtube",
    "training_plans", "apps", "books", "certifications", "science",
    "news", "podcasts", "gear", "open_water", "triathlon", "masters",
    "para", "drowning_prevention", "records", "college", "recruiting",
]

# ---------------------------------------------------------------------------
# 1. GOVERNING BODIES & FEDERATIONS
# ---------------------------------------------------------------------------

GOVERNING_BODIES: list[dict[str, Any]] = [
    # International & continental
    {"id": "gov-001", "category": "governing_bodies", "subcategory": "international",
     "name": "World Aquatics", "type": "International Federation",
     "audience": "All levels", "description": "Sets rules; sanctions World Championships and Olympic qualification across six aquatic disciplines.",
     "url": "https://www.worldaquatics.com", "pricing": "free", "region": "global", "language": "en",
     "year_founded": 1908, "status": "rebranded",
     "notes": "Founded 1908 as FINA; rebranded January 2023; HQ Lausanne.",
     "tags": ["federation", "olympics", "rules"], "verified": "2026-05"},
    {"id": "gov-002", "category": "governing_bodies", "subcategory": "international",
     "name": "LEN - European Aquatics", "type": "Continental Federation",
     "audience": "All levels", "description": "Governs 52 European federations; runs European Aquatics Championships.",
     "url": "https://www.europeanaquatics.org", "pricing": "free", "region": "europe", "language": "en",
     "year_founded": 1927, "status": "active", "notes": "",
     "tags": ["federation", "europe"], "verified": "2026-05"},
    {"id": "gov-003", "category": "governing_bodies", "subcategory": "international",
     "name": "Asia Aquatics", "type": "Continental Federation",
     "audience": "All levels", "description": "Asian Championships and Asian Games aquatics governance.",
     "url": "https://www.asiaaquatics.net", "pricing": "free", "region": "asia", "language": "en",
     "year_founded": None, "status": "rebranded", "notes": "Rebranded from AASF.",
     "tags": ["federation", "asia"], "verified": "2026-05"},
    {"id": "gov-004", "category": "governing_bodies", "subcategory": "international",
     "name": "Africa Aquatics", "type": "Continental Federation",
     "audience": "All levels", "description": "Governs 40+ African federations; African Aquatics Championships.",
     "url": "https://africaaquatics.org", "pricing": "free", "region": "africa", "language": "en",
     "year_founded": None, "status": "rebranded", "notes": "Formerly CANA. English/French.",
     "tags": ["federation", "africa"], "verified": "2026-05"},
    {"id": "gov-005", "category": "governing_bodies", "subcategory": "international",
     "name": "PanAm Aquatics", "type": "Continental Federation",
     "audience": "All levels", "description": "Pan-American Aquatics Championships; governance for the Americas.",
     "url": "https://www.panamaquatics.com", "pricing": "free", "region": "americas", "language": "en",
     "year_founded": None, "status": "rebranded",
     "notes": "Formerly ASUA/UANA; inaugural championships 2025 in Medellín.",
     "tags": ["federation", "americas"], "verified": "2026-05"},
    {"id": "gov-006", "category": "governing_bodies", "subcategory": "international",
     "name": "Oceania Aquatics", "type": "Continental Federation",
     "audience": "All levels", "description": "Governs 15 Oceania federations.",
     "url": "https://oceaniaaquatics.org", "pricing": "free", "region": "oceania", "language": "en",
     "year_founded": 1991, "status": "active", "notes": "",
     "tags": ["federation", "oceania"], "verified": "2026-05"},
    {"id": "gov-007", "category": "governing_bodies", "subcategory": "international",
     "name": "World Para Swimming", "type": "International Federation",
     "audience": "Para athletes", "description": "Paralympic governance; classification rules and World Championships.",
     "url": "https://www.paralympic.org/swimming", "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "HQ Bonn, Germany.",
     "tags": ["federation", "para", "paralympics"], "verified": "2026-05"},
    {"id": "gov-008", "category": "governing_bodies", "subcategory": "international",
     "name": "World Triathlon", "type": "International Federation",
     "audience": "Triathletes", "description": "Governs the swim leg of triathlon as part of multisport rules.",
     "url": "https://www.worldtriathlon.org", "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "HQ Lausanne.",
     "tags": ["federation", "triathlon"], "verified": "2026-05"},
    {"id": "gov-009", "category": "governing_bodies", "subcategory": "international",
     "name": "IOC - Olympic Aquatics Portal", "type": "Olympic Movement",
     "audience": "Public", "description": "Olympic.com portal for aquatics events, history, and athletes.",
     "url": "https://olympics.com/en/sports/aquatics-swimming/", "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "Recognizes World Aquatics as IF.",
     "tags": ["olympics", "history"], "verified": "2026-05"},
    {"id": "gov-010", "category": "governing_bodies", "subcategory": "international",
     "name": "International Swimming Hall of Fame (ISHOF)", "type": "Hall of Fame",
     "audience": "Historians, public", "description": "Repository of aquatic history; museum in Fort Lauderdale, FL.",
     "url": "https://ishof.org", "pricing": "free", "region": "global", "language": "en",
     "year_founded": 1965, "status": "active", "notes": "",
     "tags": ["history", "museum"], "verified": "2026-05"},
    {"id": "gov-011", "category": "governing_bodies", "subcategory": "international",
     "name": "International Marathon Swimming Hall of Fame", "type": "Hall of Fame",
     "audience": "Marathon swimmers", "description": "Honors elite open-water and marathon swimmers.",
     "url": "https://www.imshof.org", "pricing": "free", "region": "global", "language": "en",
     "year_founded": None, "status": "active", "notes": "ISHOF affiliate.",
     "tags": ["history", "open-water"], "verified": "2026-05"},
    {"id": "gov-012", "category": "governing_bodies", "subcategory": "international",
     "name": "Marathon Swimmers Federation", "type": "Federation",
     "audience": "Marathon swimmers", "description": "LongSwims database (100K+ swims); Rules of Marathon Swimming.",
     "url": "https://marathonswimmers.org", "pricing": "free", "region": "global", "language": "en",
     "year_founded": 2012, "status": "active", "notes": "",
     "tags": ["open-water", "marathon"], "verified": "2026-05"},
    {"id": "gov-013", "category": "governing_bodies", "subcategory": "international",
     "name": "International Ice Swimming Association", "type": "International Federation",
     "audience": "Ice swimmers", "description": "Ratifies Ice Miles in ≤5°C water; runs Ice Swimming World Championships.",
     "url": "https://internationaliceswimming.com", "pricing": "free", "region": "global", "language": "en",
     "year_founded": 2009, "status": "active", "notes": "Founded by Ram Barkai.",
     "tags": ["ice-swim", "extreme"], "verified": "2026-05"},

    # National federations
    {"id": "gov-101", "category": "governing_bodies", "subcategory": "national",
     "name": "USA Swimming", "type": "National Governing Body",
     "audience": "All levels", "description": "U.S. NGB; runs Olympic Trials and selects U.S. Olympic team.",
     "url": "https://www.usaswimming.org", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": 1980, "status": "active", "notes": "",
     "tags": ["federation", "usa"], "verified": "2026-05"},
    {"id": "gov-102", "category": "governing_bodies", "subcategory": "national",
     "name": "USA Swimming Foundation", "type": "Charitable Foundation",
     "audience": "Public", "description": "501(c)(3) foundation; runs Make a Splash water-safety initiative.",
     "url": "https://www.usaswimming.org/foundation", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": 2004, "status": "active", "notes": "",
     "tags": ["foundation", "water-safety"], "verified": "2026-05"},
    {"id": "gov-103", "category": "governing_bodies", "subcategory": "national",
     "name": "US Paralympics Swimming", "type": "Para NGB",
     "audience": "Para athletes", "description": "U.S. Paralympic swimming arm under USOPC.",
     "url": "https://www.usparaswimming.org", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["para", "usa"], "verified": "2026-05"},
    {"id": "gov-104", "category": "governing_bodies", "subcategory": "national",
     "name": "NCAA Swimming & Diving", "type": "Collegiate Governance",
     "audience": "College athletes", "description": "Governance and championship structure for U.S. collegiate swimming.",
     "url": "https://www.ncaa.com/sports/swimming-men", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "Women's portal: /swimming-women",
     "tags": ["college", "ncaa"], "verified": "2026-05"},
    {"id": "gov-105", "category": "governing_bodies", "subcategory": "national",
     "name": "NFHS - National Federation of State High School Associations", "type": "High School Governance",
     "audience": "High school athletes", "description": "U.S. high school sport rules including swimming and diving.",
     "url": "https://www.nfhs.org", "pricing": "free", "region": "USA", "language": "en",
     "year_founded": 1920, "status": "active", "notes": "",
     "tags": ["high-school", "rules"], "verified": "2026-05"},
    {"id": "gov-106", "category": "governing_bodies", "subcategory": "national",
     "name": "NISCA - National Interscholastic Swimming Coaches Association", "type": "Coaches Association",
     "audience": "HS coaches", "description": "U.S. high school swimming coaches association.",
     "url": "https://www.niscaonline.org", "pricing": "mixed", "region": "USA", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["coaches", "high-school"], "verified": "2026-05"},
    {"id": "gov-107", "category": "governing_bodies", "subcategory": "national",
     "name": "Aquatics GB", "type": "National Governing Body",
     "audience": "All levels", "description": "GB national governing body for elite swimming.",
     "url": "https://www.britishswimming.org", "pricing": "free", "region": "GB", "language": "en",
     "year_founded": None, "status": "rebranded", "notes": "Rebranded from British Swimming in 2024.",
     "tags": ["federation", "gb"], "verified": "2026-05"},
    {"id": "gov-108", "category": "governing_bodies", "subcategory": "national",
     "name": "Swim England", "type": "National Federation",
     "audience": "All levels", "description": "Governing body for swimming in England; world's oldest swim federation.",
     "url": "https://www.swimming.org", "pricing": "free", "region": "England", "language": "en",
     "year_founded": 1869, "status": "active", "notes": "",
     "tags": ["federation", "england"], "verified": "2026-05"},
    {"id": "gov-109", "category": "governing_bodies", "subcategory": "national",
     "name": "Scottish Swimming", "type": "National Federation",
     "audience": "All levels", "description": "Governing body for swimming in Scotland.",
     "url": "https://www.scottishswimming.com", "pricing": "free", "region": "Scotland", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "scotland"], "verified": "2026-05"},
    {"id": "gov-110", "category": "governing_bodies", "subcategory": "national",
     "name": "Swim Wales", "type": "National Federation",
     "audience": "All levels", "description": "Governing body for swimming in Wales.",
     "url": "https://www.swimwales.org", "pricing": "free", "region": "Wales", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "wales"], "verified": "2026-05"},
    {"id": "gov-111", "category": "governing_bodies", "subcategory": "national",
     "name": "Swim Ireland", "type": "National Federation",
     "audience": "All levels", "description": "All-island governing body for swimming in Ireland.",
     "url": "https://swimireland.ie", "pricing": "free", "region": "Ireland", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "ireland"], "verified": "2026-05"},
    {"id": "gov-112", "category": "governing_bodies", "subcategory": "national",
     "name": "Swim Ulster", "type": "Regional Federation",
     "audience": "All levels", "description": "Northern Ireland regional swimming body.",
     "url": "https://www.swimulster.com", "pricing": "free", "region": "N. Ireland", "language": "en",
     "year_founded": 1893, "status": "active", "notes": "",
     "tags": ["federation"], "verified": "2026-05"},
    {"id": "gov-113", "category": "governing_bodies", "subcategory": "national",
     "name": "Swimming Canada", "type": "National Governing Body",
     "audience": "All levels", "description": "Bilingual NGB for swimming in Canada.",
     "url": "https://www.swimming.ca", "pricing": "free", "region": "Canada", "language": "en",
     "year_founded": None, "status": "active", "notes": "Bilingual EN/FR.",
     "tags": ["federation", "canada"], "verified": "2026-05"},
    {"id": "gov-114", "category": "governing_bodies", "subcategory": "national",
     "name": "Swimming Australia", "type": "National Governing Body",
     "audience": "All levels", "description": "NGB for elite swimming in Australia.",
     "url": "https://www.swimming.org.au", "pricing": "free", "region": "Australia", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "australia"], "verified": "2026-05"},
    {"id": "gov-115", "category": "governing_bodies", "subcategory": "national",
     "name": "Swimming New Zealand", "type": "National Governing Body",
     "audience": "All levels", "description": "NGB for swimming in New Zealand.",
     "url": "https://www.swimming.org.nz", "pricing": "free", "region": "NZ", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "new-zealand"], "verified": "2026-05"},
    {"id": "gov-116", "category": "governing_bodies", "subcategory": "national",
     "name": "Japan Aquatics", "type": "National Federation",
     "audience": "All levels", "description": "Japan's national aquatic sports federation.",
     "url": "https://aquatics.or.jp", "pricing": "free", "region": "Japan", "language": "ja",
     "year_founded": None, "status": "rebranded",
     "notes": "Rebranded from JASF in April 2025.",
     "tags": ["federation", "japan"], "verified": "2026-05"},
    {"id": "gov-117", "category": "governing_bodies", "subcategory": "national",
     "name": "Japan Para-Swimming Federation", "type": "National Para Federation",
     "audience": "Para athletes", "description": "Japan's para-swimming governing body.",
     "url": "https://paraswim.jp", "pricing": "free", "region": "Japan", "language": "ja",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "para", "japan"], "verified": "2026-05"},
    {"id": "gov-118", "category": "governing_bodies", "subcategory": "national",
     "name": "Chinese Swimming Association", "type": "National Federation",
     "audience": "All levels", "description": "China's national swimming association.",
     "url": "https://chinaaquatics.org.cn", "pricing": "free", "region": "China", "language": "zh",
     "year_founded": None, "status": "active", "notes": "New 2026 portal.",
     "tags": ["federation", "china"], "verified": "2026-05"},
    {"id": "gov-119", "category": "governing_bodies", "subcategory": "national",
     "name": "Korea Aquatics", "type": "National Federation",
     "audience": "All levels", "description": "South Korea's national aquatics federation.",
     "url": "https://www.korswim.co.kr", "pricing": "free", "region": "S. Korea", "language": "ko",
     "year_founded": None, "status": "rebranded", "notes": "Rebranded from KSF in February 2024.",
     "tags": ["federation", "korea"], "verified": "2026-05"},
    {"id": "gov-120", "category": "governing_bodies", "subcategory": "national",
     "name": "Singapore Aquatics", "type": "National Federation",
     "audience": "All levels", "description": "Singapore's national aquatics governing body; hosted 2025 Worlds.",
     "url": "https://www.sgaquatics.org.sg", "pricing": "free", "region": "Singapore", "language": "en",
     "year_founded": None, "status": "rebranded",
     "notes": "Rebranded from Singapore Swimming Association in July 2023.",
     "tags": ["federation", "singapore"], "verified": "2026-05"},
    {"id": "gov-121", "category": "governing_bodies", "subcategory": "national",
     "name": "FFN - Fédération Française de Natation", "type": "National Federation",
     "audience": "All levels", "description": "French national swimming federation.",
     "url": "https://www.ffnatation.fr", "pricing": "free", "region": "France", "language": "fr",
     "year_founded": 1919, "status": "active", "notes": "",
     "tags": ["federation", "france"], "verified": "2026-05"},
    {"id": "gov-122", "category": "governing_bodies", "subcategory": "national",
     "name": "DSV - Deutscher Schwimm-Verband", "type": "National Federation",
     "audience": "All levels", "description": "German swimming federation; ~600K members.",
     "url": "https://www.dsv.de", "pricing": "free", "region": "Germany", "language": "de",
     "year_founded": 1886, "status": "active", "notes": "",
     "tags": ["federation", "germany"], "verified": "2026-05"},
    {"id": "gov-123", "category": "governing_bodies", "subcategory": "national",
     "name": "FIN - Federazione Italiana Nuoto", "type": "National Federation",
     "audience": "All levels", "description": "Italian swimming federation.",
     "url": "https://www.federnuoto.it", "pricing": "free", "region": "Italy", "language": "it",
     "year_founded": 1899, "status": "active", "notes": "",
     "tags": ["federation", "italy"], "verified": "2026-05"},
    {"id": "gov-124", "category": "governing_bodies", "subcategory": "national",
     "name": "KNZB - Royal Dutch Swimming Federation", "type": "National Federation",
     "audience": "All levels", "description": "Dutch national swimming federation.",
     "url": "https://www.knzb.nl", "pricing": "free", "region": "Netherlands", "language": "nl",
     "year_founded": 1888, "status": "active", "notes": "",
     "tags": ["federation", "netherlands"], "verified": "2026-05"},
    {"id": "gov-125", "category": "governing_bodies", "subcategory": "national",
     "name": "MÚSZ - Hungarian Swimming Association", "type": "National Federation",
     "audience": "All levels", "description": "Hungarian national swimming association.",
     "url": "https://musz.hu", "pricing": "free", "region": "Hungary", "language": "hu",
     "year_founded": 1907, "status": "active", "notes": "English mirror: https://hunswim.com/en",
     "tags": ["federation", "hungary"], "verified": "2026-05"},
    {"id": "gov-126", "category": "governing_bodies", "subcategory": "national",
     "name": "All-Russian Swimming Federation", "type": "National Federation",
     "audience": "All levels", "description": "Russian national swimming federation.",
     "url": "https://russwimming.ru", "pricing": "free", "region": "Russia", "language": "ru",
     "year_founded": None, "status": "active",
     "notes": "International sanctions limit competition participation.",
     "tags": ["federation", "russia"], "verified": "2026-05"},
    {"id": "gov-127", "category": "governing_bodies", "subcategory": "national",
     "name": "CBDA - Confederação Brasileira de Desportos Aquáticos", "type": "National Federation",
     "audience": "All levels", "description": "Brazilian aquatic sports confederation.",
     "url": "https://www.cbda.org.br", "pricing": "free", "region": "Brazil", "language": "pt",
     "year_founded": 1977, "status": "active", "notes": "",
     "tags": ["federation", "brazil"], "verified": "2026-05"},
    {"id": "gov-128", "category": "governing_bodies", "subcategory": "national",
     "name": "Swimming South Africa", "type": "National Federation",
     "audience": "All levels", "description": "National swimming federation of South Africa.",
     "url": "https://swimsa.org", "pricing": "free", "region": "South Africa", "language": "en",
     "year_founded": None, "status": "active", "notes": "",
     "tags": ["federation", "south-africa"], "verified": "2026-05"},
]
