"""Data part 7: open water + triathlon + masters."""
from __future__ import annotations
from typing import Any

# ---------------------------------------------------------------------------
# 13. OPEN WATER & MARATHON SWIMMING
# ---------------------------------------------------------------------------

OPEN_WATER: list[dict[str, Any]] = [
    {"id": "ow-001", "category": "open_water", "name": "Marathon Swimmers Federation",
     "type": "Federation", "audience": "Marathon swimmers",
     "description": "LongSwims database (100K+ swims since 1875); Rules of Marathon Swimming.",
     "url": "https://marathonswimmers.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2012, "status": "active", "notes": "",
     "tags": ["open-water", "marathon"], "verified": "2026-05"},
    {"id": "ow-002", "category": "open_water", "name": "World Open Water Swimming Association (WOWSA)",
     "type": "Association", "audience": "Open-water swimmers",
     "description": "Global association; OpenWaterPedia encyclopedia and tiered coach certifications.",
     "url": "https://www.openwaterswimming.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "association"], "verified": "2026-05"},
    {"id": "ow-003", "category": "open_water", "name": "Channel Swimming Association",
     "type": "Channel Authority", "audience": "Channel aspirants",
     "description": "Original 1927 English Channel ratification body.",
     "url": "https://www.channelswimmingassociation.com",
     "pricing": "paid", "region": "UK", "language": "en", "year_founded": 1927,
     "status": "active", "notes": "",
     "tags": ["open-water", "english-channel"], "verified": "2026-05"},
    {"id": "ow-004", "category": "open_water", "name": "Channel Swimming & Piloting Federation",
     "type": "Channel Authority", "audience": "Channel aspirants",
     "description": "Alternative English Channel ratification body.",
     "url": "https://cspf.co.uk", "pricing": "paid", "region": "UK",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "english-channel"], "verified": "2026-05"},
    {"id": "ow-005", "category": "open_water", "name": "Catalina Channel Swimming Federation",
     "type": "Channel Authority", "audience": "Catalina aspirants",
     "description": "Ratifying body for Catalina Channel crossings.",
     "url": "https://www.swimcatalina.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "catalina"], "verified": "2026-05"},
    {"id": "ow-006", "category": "open_water", "name": "NYC Swim / NY Open Water",
     "type": "Race Organizer", "audience": "Open-water swimmers",
     "description": "Manhattan 20 Bridges and other NYC swims.",
     "url": "https://nyopenwater.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "races"], "verified": "2026-05"},
    {"id": "ow-007", "category": "open_water", "name": "International Marathon Swimming Hall of Fame",
     "type": "Hall of Fame", "audience": "Public",
     "description": "Honors elite marathon swimmers.",
     "url": "https://www.imshof.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "history"], "verified": "2026-05"},
    {"id": "ow-008", "category": "open_water", "name": "International Ice Swimming Association",
     "type": "International Federation", "audience": "Ice swimmers",
     "description": "Ratifies Ice Miles in ≤5°C water; runs Ice Worlds.",
     "url": "https://internationaliceswimming.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 2009, "status": "active", "notes": "",
     "tags": ["open-water", "ice-swim"], "verified": "2026-05"},
    {"id": "ow-009", "category": "open_water", "name": "International Winter Swimming Association",
     "type": "International Federation", "audience": "Winter swimmers",
     "description": "Winter swimming governance.",
     "url": "https://iwsa.world", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "winter"], "verified": "2026-05"},
    {"id": "ow-010", "category": "open_water", "name": "Daily News of Open Water Swimming",
     "type": "News Site", "audience": "Public",
     "description": "Daily news from open-water community (WOWSA).",
     "url": "https://dailynewsofopenwaterswimming.com",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["open-water", "news"], "verified": "2026-05"},
    {"id": "ow-011", "category": "open_water", "name": "OpenWaterPedia",
     "type": "Encyclopedia", "audience": "Public",
     "description": "Open-water swimming encyclopedia maintained by WOWSA.",
     "url": "https://openwaterpedia.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "reference"], "verified": "2026-05"},
    {"id": "ow-012", "category": "open_water", "name": "Oceans Seven",
     "type": "Challenge", "audience": "Channel swimmers",
     "description": "Marathon-swimming equivalent of the Seven Summits.",
     "url": "https://en.wikipedia.org/wiki/Oceans_Seven", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["open-water", "challenge"], "verified": "2026-05"},
    {"id": "ow-013", "category": "open_water", "name": "Outdoor Swimmer (UK)",
     "type": "Magazine", "audience": "Open-water swimmers",
     "description": "UK magazine for outdoor and open-water swimmers since 2011.",
     "url": "https://outdoorswimmer.com", "pricing": "mixed", "region": "UK",
     "language": "en", "year_founded": 2011, "status": "active", "notes": "",
     "tags": ["open-water", "magazine"], "verified": "2026-05"},
    {"id": "ow-014", "category": "open_water", "name": "Swim England Open Water",
     "type": "Federation Resource", "audience": "Open-water swimmers",
     "description": "Open-water content from Swim England.",
     "url": "https://www.swimming.org/openwater", "pricing": "free", "region": "England",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "federation"], "verified": "2026-05"},
    {"id": "ow-015", "category": "open_water", "name": "SwimTrek",
     "type": "Adventure Travel", "audience": "All",
     "description": "Open-water swimming holidays in 30+ destinations.",
     "url": "https://www.swimtrek.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "travel"], "verified": "2026-05"},
    {"id": "ow-016", "category": "open_water", "name": "Swim the Suck",
     "type": "Race", "audience": "Distance swimmers",
     "description": "10-mile Tennessee River race in Chattanooga, TN.",
     "url": "https://swimthesuck.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "race"], "verified": "2026-05"},
    {"id": "ow-017", "category": "open_water", "name": "Swim Around Key West",
     "type": "Race", "audience": "Distance swimmers",
     "description": "12.5-mile circumnavigation race in Key West, FL.",
     "url": "https://swimaroundkeywest.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "race"], "verified": "2026-05"},
    {"id": "ow-018", "category": "open_water", "name": "Lynne Cox official site",
     "type": "Author", "audience": "Public",
     "description": "Official site of pioneering open-water swimmer and author.",
     "url": "https://lynnecox.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "author"], "verified": "2026-05"},
    {"id": "ow-019", "category": "open_water", "name": "World Aquatics Open Water",
     "type": "Federation", "audience": "Elite",
     "description": "World Cup and 10K Marathon Swim governance.",
     "url": "https://www.worldaquatics.com/swimming/open-water-swimming",
     "pricing": "free", "region": "global", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["open-water", "federation"], "verified": "2026-05"},
    {"id": "ow-020", "category": "open_water", "name": "FINA / World Aquatics Open Water Rules",
     "type": "Reference Document", "audience": "All",
     "description": "Official open-water rules document from World Aquatics.",
     "url": "https://www.worldaquatics.com/rules", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["open-water", "rules"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 14. TRIATHLON SWIMMING
# ---------------------------------------------------------------------------

TRIATHLON: list[dict[str, Any]] = [
    {"id": "tri-001", "category": "triathlon", "name": "World Triathlon",
     "type": "International Federation", "audience": "Triathletes",
     "description": "International federation for triathlon and multisport.",
     "url": "https://www.worldtriathlon.org", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "federation"], "verified": "2026-05"},
    {"id": "tri-002", "category": "triathlon", "name": "USA Triathlon",
     "type": "National Federation", "audience": "US triathletes",
     "description": "U.S. national governing body for triathlon.",
     "url": "https://www.usatriathlon.org", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "federation"], "verified": "2026-05"},
    {"id": "tri-003", "category": "triathlon", "name": "British Triathlon",
     "type": "National Federation", "audience": "GB triathletes",
     "description": "GB national governing body for triathlon.",
     "url": "https://www.britishtriathlon.org", "pricing": "free", "region": "GB",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "federation"], "verified": "2026-05"},
    {"id": "tri-004", "category": "triathlon", "name": "Triathlon Australia",
     "type": "National Federation", "audience": "AUS triathletes",
     "description": "Australia's national triathlon federation.",
     "url": "https://www.triathlon.org.au", "pricing": "free", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "federation"], "verified": "2026-05"},
    {"id": "tri-005", "category": "triathlon", "name": "Slowtwitch",
     "type": "News + Forum", "audience": "Triathletes",
     "description": "Long-running triathlon news, forum, and reviews.",
     "url": "https://www.slowtwitch.com", "pricing": "free", "region": "global",
     "language": "en", "year_founded": 1999, "status": "active", "notes": "",
     "tags": ["triathlon", "news"], "verified": "2026-05"},
    {"id": "tri-006", "category": "triathlon", "name": "BeginnerTriathlete",
     "type": "Forum + Plans", "audience": "New triathletes",
     "description": "Beginner-friendly community and training plans.",
     "url": "https://www.beginnertriathlete.com", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "beginners"], "verified": "2026-05"},
    {"id": "tri-007", "category": "triathlon", "name": "Effortless Swimming for Triathletes",
     "type": "Coaching Program", "audience": "Triathletes",
     "description": "Triathlon-specific stroke-analysis and membership program.",
     "url": "https://effortlessswimming.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "technique"], "verified": "2026-05"},
    {"id": "tri-008", "category": "triathlon", "name": "Swim Smooth for Triathletes",
     "type": "Methodology", "audience": "Triathletes",
     "description": "Swim Smooth's triathlon-focused content; British Triathlon partner.",
     "url": "https://www.swimsmooth.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "technique"], "verified": "2026-05"},
    {"id": "tri-009", "category": "triathlon", "name": "TrainerRoad",
     "type": "Training App", "audience": "Triathletes/cyclists",
     "description": "Adaptive endurance training; primarily cycling but used by triathletes.",
     "url": "https://www.trainerroad.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "training"], "verified": "2026-05"},
    {"id": "tri-010", "category": "triathlon", "name": "TriDot",
     "type": "AI Training Platform", "audience": "Triathletes",
     "description": "AI-driven triathlon training; IRONMAN partner.",
     "url": "https://www.tridot.com", "pricing": "paid", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "training", "ai"], "verified": "2026-05"},
    {"id": "tri-011", "category": "triathlon", "name": "220 Triathlon Magazine",
     "type": "Magazine", "audience": "Triathletes",
     "description": "UK triathlon magazine since 1989.",
     "url": "https://www.220triathlon.com", "pricing": "mixed", "region": "UK",
     "language": "en", "year_founded": 1989, "status": "active", "notes": "",
     "tags": ["triathlon", "magazine"], "verified": "2026-05"},
    {"id": "tri-012", "category": "triathlon", "name": "IRONMAN Training Plans",
     "type": "Plans", "audience": "Triathletes",
     "description": "Official IRONMAN training-plan library.",
     "url": "https://www.ironman.com/training", "pricing": "freemium", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "plans"], "verified": "2026-05"},
    {"id": "tri-013", "category": "triathlon", "name": "Triathlete Magazine",
     "type": "Magazine", "audience": "Triathletes",
     "description": "U.S.-based triathlon magazine with training and gear coverage.",
     "url": "https://www.triathlete.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "magazine"], "verified": "2026-05"},
    {"id": "tri-014", "category": "triathlon", "name": "Tri Swim Coach",
     "type": "Coaching Program", "audience": "Triathletes",
     "description": "Triathlon-swim coaching from Kevin Koskella.",
     "url": "https://www.triswimcoach.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "coaching"], "verified": "2026-05"},
    {"id": "tri-015", "category": "triathlon", "name": "Scientific Triathlon",
     "type": "Coaching + Podcast", "audience": "Triathletes",
     "description": "Mikael Eriksson's coaching plus That Triathlon Show podcast.",
     "url": "https://scientifictriathlon.com", "pricing": "mixed", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["triathlon", "coaching", "podcast"], "verified": "2026-05"},
]


# ---------------------------------------------------------------------------
# 15. MASTERS SWIMMING
# ---------------------------------------------------------------------------

MASTERS: list[dict[str, Any]] = [
    {"id": "mas-001", "category": "masters", "name": "U.S. Masters Swimming (USMS)",
     "type": "National NGB", "audience": "Adults 18+",
     "description": "U.S. NGB for adult swimming; ~50K members across 600+ clubs.",
     "url": "https://www.usms.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": 1970, "status": "active", "notes": "",
     "tags": ["masters", "ngb"], "verified": "2026-05"},
    {"id": "mas-002", "category": "masters", "name": "USMS Coach Certification",
     "type": "Coach Certification", "audience": "Masters coaches",
     "description": "Tiered USMS coach certification (L1–4).",
     "url": "https://www.usms.org/coach-central", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "certification"], "verified": "2026-05"},
    {"id": "mas-003", "category": "masters", "name": "Streamlines (USMS Magazine)",
     "type": "Member Magazine", "audience": "USMS members",
     "description": "USMS member magazine.",
     "url": "https://www.usms.org/news/streamlines", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active",
     "notes": "USMS member benefit.",
     "tags": ["masters", "magazine"], "verified": "2026-05"},
    {"id": "mas-004", "category": "masters", "name": "USMS Records & Top 10",
     "type": "Records Database", "audience": "Public",
     "description": "USMS national records and Top-10 listings.",
     "url": "https://www.usms.org/comp/records-tt",
     "pricing": "free", "region": "USA", "language": "en", "year_founded": None,
     "status": "active", "notes": "",
     "tags": ["masters", "records"], "verified": "2026-05"},
    {"id": "mas-005", "category": "masters", "name": "Swim England Masters",
     "type": "Federation Resource", "audience": "UK masters",
     "description": "Masters portal from Swim England.",
     "url": "https://www.swimming.org/masters", "pricing": "free", "region": "England",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-006", "category": "masters", "name": "Aquatics GB Masters",
     "type": "Federation Resource", "audience": "GB masters",
     "description": "Masters resources from Aquatics GB.",
     "url": "https://www.britishswimming.org/masters", "pricing": "free", "region": "GB",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-007", "category": "masters", "name": "Masters Swimming Canada",
     "type": "National Federation", "audience": "Canadian masters",
     "description": "Canadian masters swimming national body.",
     "url": "https://www.mastersswimmingcanada.ca", "pricing": "paid", "region": "Canada",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-008", "category": "masters", "name": "Swimming Canada Masters",
     "type": "Federation Resource", "audience": "Canadian masters",
     "description": "Masters portal from Swimming Canada.",
     "url": "https://www.swimming.ca/en/masters/", "pricing": "free", "region": "Canada",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-009", "category": "masters", "name": "Masters Swimming Australia",
     "type": "National Federation", "audience": "AUS masters",
     "description": "Australia's masters swimming federation.",
     "url": "https://mastersswimming.org.au", "pricing": "paid", "region": "Australia",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-010", "category": "masters", "name": "World Aquatics Masters",
     "type": "International Federation", "audience": "Global masters",
     "description": "World Aquatics Masters Championships and program.",
     "url": "https://www.worldaquatics.com/swimming/masters", "pricing": "free",
     "region": "global", "language": "en", "year_founded": None, "status": "active",
     "notes": "",
     "tags": ["masters", "federation"], "verified": "2026-05"},
    {"id": "mas-011", "category": "masters", "name": "LEN Masters",
     "type": "Continental Federation", "audience": "European masters",
     "description": "European Aquatics Masters Championships.",
     "url": "https://www.europeanaquatics.org", "pricing": "free", "region": "europe",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "europe"], "verified": "2026-05"},
    {"id": "mas-012", "category": "masters", "name": "Masters International Swimming Hall of Fame",
     "type": "Hall of Fame", "audience": "Public",
     "description": "MISHOF - masters branch of ISHOF.",
     "url": "https://ishof.org/mishof.html", "pricing": "free", "region": "global",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "history"], "verified": "2026-05"},
    {"id": "mas-013", "category": "masters", "name": "Pacific Masters Swimming",
     "type": "USMS LMSC", "audience": "California masters",
     "description": "Largest USMS Local Masters Swimming Committee (Northern California).",
     "url": "https://www.pacificmasters.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "usa"], "verified": "2026-05"},
    {"id": "mas-014", "category": "masters", "name": "Southern Pacific Masters Swimming",
     "type": "USMS LMSC", "audience": "SoCal masters",
     "description": "Southern California USMS LMSC.",
     "url": "https://www.spmaswim.org", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "usa"], "verified": "2026-05"},
    {"id": "mas-015", "category": "masters", "name": "New England Masters Swimming",
     "type": "USMS LMSC", "audience": "New England masters",
     "description": "USMS LMSC for the New England region.",
     "url": "https://www.nemsswim.com", "pricing": "paid", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "usa"], "verified": "2026-05"},
    {"id": "mas-016", "category": "masters", "name": "USMS Club Finder",
     "type": "Tool", "audience": "Public",
     "description": "Search tool for finding USMS workout groups by location.",
     "url": "https://www.usms.org/clubs", "pricing": "free", "region": "USA",
     "language": "en", "year_founded": None, "status": "active", "notes": "",
     "tags": ["masters", "directory"], "verified": "2026-05"},
]
